### ISSUE TITLE
Crash in thread::~thread() on Huawei

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/mobile#1060]
Seems to happen when user tries to exit with the android back button. Only Huawei seems affected.

Not specific to Input - other apps seem to have this problem as well:
https://bugreports.qt.io/browse/QTBUG-82617
https://bugreports.qt.io/browse/QTBUG-85449

**Comment by PeterPetrik** [comment]
this is probably critical discussion: https://codereview.qt-project.org/c/qt/qtbase/+/318099

**Comment by tomasMizera** [comment]
https://developernote.com/2022/03/crash-at-std-thread-and-std-mutex-destructors-on-android/#comment-694101

**Comment by tomasMizera** [comment]
Can't see it in logs anymore :)
