### ISSUE TITLE
android Unsupported APIs

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/mobile#1068]
disturbing: https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces

20 different calls for "Unsupported APIs"

Unsupported APIs aren't guaranteed to work on current or future versions of Android. They may be restricted in future Android releases.

all coming from qt 5.14.2
```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/R$styleable;->TextView
at org.qtproject.qt5.android.ExtractStyle.extractTextAppearanceInformations(ExtractStyle.java:1329)
```

probably related: https://bugreports.qt.io/browse/QTBUG-71590

**Comment by PeterPetrik** [comment]
We are on Qt 6.x where it should be fixed

**Comment by tomasMizera** [comment]
The number of such calls is reduced, but there are some still.

**Comment by tomasMizera** [comment]
Should be fine now
