### ISSUE TITLE
Losing internet connection behaviour

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#1092]
Input do not react reasonable when running it without internet connection.

Projects lists says "No projects found" as if no projects exist (my, shared, explore).

Login screen says "please update input to newest version"

**Comment by dracic** [comment]
The other thing when losing connection and going to "Projects" windows is that Mergin credentials are lost. You have to enter them again...

**Comment by tomasMizera** [comment]
There are multiple issues connected, both UI and UX. 
Would be best to have some dedicated service that would ping each X seconds Mergin or Google endpoint and emit signal about internet connection failures.

**Comment by wonder-sk** [comment]
Recently there were updates to improve the app's behavior when it is not online - closing for now...
