### ISSUE TITLE
Map tip for images cannot span multiple lines

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/mobile#1106]
Loader::mapTipImage() only considers the second line of map tip. But if someone uses an embedded expression on multiple lines, things don't work correctly.

E.g. 
```
# image
file:///my/path/to/image/[%
  CASE WHEN x = 1 THEN
    'hello.jpg'
  ELSE
    'world.jpg'
  END
%]
```

cc @mostlyAtNight

**Comment by jozef-budac** [comment]
Verified  on 2024.3.0 RC
