### ISSUE TITLE
Form tabs not following along when swiping through tabs

### ISSUE THREAD

**Issue by HugoP27** [MerginMaps/mobile#1112]
Hi Input team, very small bug, but when you have many tabs in a layers' form and you swipe from right to left on the form to scroll through each tab (instead of clicking on each tab to view it), the tabs that are not in view (due to the width of the phone) do not scroll into view once you reach the tab form![Screenshot_20210126_233449_uk.co.lutraconsulting.jpg](https://user-images.githubusercontent.com/51097011/105908636-21b26180-602f-11eb-8949-9957b89d61a0.jpg)```

```

**Comment by saberraz** [comment]
related to #1353

**Comment by jozef-budac** [comment]
Still present. You can see it in input-testing/forms_widgets project

**Comment by PeterPetrik** [comment]
@jozef-budac is this still issue with 2024.1.0?

**Comment by jozef-budac** [comment]
No, this issue is not present in 2024.1.0.
