### ISSUE TITLE
Sorting of the list in "Browse features"

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/mobile#1199]
Currently we do not have any order for layer features in the list.

It would be good to alphabetically order the features, so it is easier for people to navigate through the list (when not using search).

Or maybe it should be upon a request to sort the list ascending/descending based on a column?

**Comment by timlinux** [comment]
Perhaps a widget at the top to toggle between 'natural', asc, desc ?

**Comment by CharlesGag** [comment]
I think this would be a really important feature. I think it always order everything by FID if I'm not wrong ? Would be nice it if would follow the display name set in the layer properties, or as @timlinux said to be able to switch between a few sort options. Best case scenario would be  a customisable sort option like in QGIS :

![image](https://github.com/MerginMaps/mobile/assets/104785205/89d9be0c-899e-4bbd-b1cd-73ec9c71a66a)

Thank you

**Comment by alexd0793** [comment]
Failed because sorting is not happening as per https://github.com/MerginMaps/mobile/issues/3604
