### ISSUE TITLE
Form justification and alignment for geometry-less table

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#1261]
It looks to me that the forms for geometry-less tables are not properly aligned and justified. There seems to much gap between the field header and the field value:
![Screenshot_20210312-174500](https://user-images.githubusercontent.com/2649047/110978407-3f2b5880-835b-11eb-8479-7e8f04f6d638.png)

**Comment by tomasMizera** [comment]
Can you still see this in the app @saberraz?

**Comment by jozef-budac** [comment]
@saberraz do you have a project, where I can retest this? Or I can prepare project to try it
