### ISSUE TITLE
Adding new points based on map position not by gps position

### ISSUE THREAD

**Issue by tosiek12** [MerginMaps/mobile#1268]
It would be usefull to have option in configuration to disable moving map to gps location during recording new point.
New point should be then added in center of current location (crosshair should be initialized by current map location not by gps position).

**Use case:** adding multiple points from one place (being safe in side of the road). After clicking record we always must move to proper location...

**Other solution:** handle hold on map event -> when pressing record map moves to gps location, when holding on map precise postion new point is added exacly in selected point (form is open directly without showing crosshair)

**Comment by saberraz** [comment]
You can move the map when in recording mode. It will change the location to where you want and not on the GPS.

**Comment by tosiek12** [comment]
Yes, I know it. The problem is, when I must add multiple points in remote area (different than my current gps location). After turning recording mode I'm always initialized at gps location and must move map multiple times into desired location.

Found some hack - when i turn off access to gps for this application then turning record mode init in current location - but it requires some additional action in phone that must be reverted afterwards...

**Comment by saberraz** [comment]
This is the desired behaviour (centre around gps) for most use cases. The app also supports moving/panning the map to the location elsewhere which is not your current GPS location. Not sure if we can add more buttons/function to support extra workflows.

**Comment by tosiek12** [comment]
I see... But still when i click record it moves me to current gps position.
This hack solves my problem, but still in field most the time i look into the map and find accurate place I need to store and then click record and then is this 'daamn, not again' moment because I need search this place again :) 

It's more nice to have feature. Maybe it could be connected with option map follows gps? When its on record moves into gps, and when off it stars on current map center?

**Comment by baswein** [comment]
I would also like this as a setting. I understand why in most use cases having the cross hairs go to the current GPS location is the right setting as most users are in the field at the location of the point being taken or close by. However I have often found I want to add new points or polygons from my phone or tablet when I am not on site. This can be very awkward. In these cases a setting called "Go to GPS location" in the Recording settings that can be toggled off similar to "Follow GPS with map".

**Comment by wonder-sk** [comment]
Agreed this would be useful.

Just an idea - another option would be to allow disabling GPS when it's not needed. This would 1. save some battery, and 2. disable automatic move of the map to the current position.

**Comment by tomasMizera** [comment]
Implemented now - you can access this setting in the app settings
