### ISSUE TITLE
Menu with overlapping texts

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#1355]
For German users, there is overlapping text (Zoom to project extent) on  moto g8:
![Screenshot_20210423-225226](https://user-images.githubusercontent.com/2649047/115949161-e4912a80-a4ca-11eb-9145-bddbeca897ef.png)

**Comment by jozef-budac** [comment]
There is one more overlapping error with Diagnostic log. 
In German there is a "An die Entwickler senden" button and it goes out the borders

**Comment by PeterPetrik** [comment]
we have new Toolbar in 2024.1.0, reopen if it is still an issue
