### ISSUE TITLE
Feature details can't be displayed

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#1429]
App version 0.9.7.

There is problem with displaying longer strings for feature fields. 
In portrait mode, it goes out of window.
In landscape mode, fields can be under the window and it can't be scrolled up.

There should be some way to see it better without entering the edit mode for feature.

https://user-images.githubusercontent.com/83582181/119645894-d06c8000-be1e-11eb-9ca9-7e28bad95652.mp4

**Comment by tomasMizera** [comment]
This is fixed in a way that it does not run out of the screen. Better fix will be introduced in the UI redesign #2878
