### ISSUE TITLE
Loading bar keeps loading

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#1432]
When GPS active press record button, loading bar on the top of the page keeps loading something even when everything looks ok.

https://user-images.githubusercontent.com/83582181/119698420-8224a480-be51-11eb-9ada-fce28bb8fb86.mp4

**Comment by saberraz** [comment]
To replicate:
1- Press record
2- Pan the map
3- Press GPS to recenter around the GPS
4- Map keeps refreshing

**Comment by sklencar** [comment]
Canvas loading indicator listens on `QgsQuickMapCanvasMap::mapCanvasRefreshed` signal emitted on rendering the canvas. Rendering of the canvas is trigged by following the GPS position (e.g while recording or having centered mode on). Even small changes in position can trigger updating a map, regardless on zoom level.

Do we want to introduce a trashhold value (or any condition) for such update, so if a change of canvas is hardly noticeable, the indicator will not be shown? If yes, what behaviour (and condition) is expected?

Another inconvenient thing is that the canvas indicator can be visible on different pages while updating canvas due GPS change (e.g user has active project, canvas is updating on GPS change, but projects page or any other page is opened).
Do we want to forbid the canvas to be updated while is not visible?

**Comment by wonder-sk** [comment]
We need to think about what's best thing to do. I see two main directions:
- keep the crosshair always in the center - we may want to render map also with some margins, so that small movement of the map will not need map redraws
- let the crosshair move away from the center - in this case we would not move the map automatically, only when the GPS position would be getting out of the view

**Comment by sklencar** [comment]
There are two cases when user does nothing, but canvas loading indicator can be (unexpectedly) shown:
1. automatic recording with gps
2. having project open and have centered mode on

I think the 2. direction is in contradiction with 2. case.
Best to discuss all cases, importance of indicator and expected/acceptable behaviour.

**Comment by PeterPetrik** [comment]
Is this still an issue @jozef-budac ?
