### ISSUE TITLE
Forms: everything above or below tabs is not displayed

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#1458]
In more complex form, where there are fields above and under Tabs, this fields are ignored in the INPUT
But probably this is known problem.

**Comment by wonder-sk** [comment]
Yes, this is known and probably it will intentionally stay as it is for the time being. There is a ticket from mergin plugin to help users to understand unsupported features: https://github.com/lutraconsulting/qgis-mergin-plugin/issues/259
