### ISSUE TITLE
Forms and value relation

### ISSUE THREAD

**Issue by BoswachterMarc** [MerginMaps/mobile#1459]
Hi, it looks like the Input app (v0.9.7) can't handle forms and container groups with field display based on other values.
See [this post](https://gis.stackexchange.com/questions/332621/qgis-forms-field-display-based-on-the-value-of-another-field/332719#332719).
In this project, one must first enter a value in a 'Type' field before the corresponding form shows up.

In QGis 3.16 and QField 1.9.6  it works fine.
Could you have a look at this? Thank you.

![Schermafdruk_2021-06-07_13-41-26](https://user-images.githubusercontent.com/57868975/121010798-2386f100-c796-11eb-8dab-82683a694a5c.png)
_Screenshot drag and drop designer form lay-out_

![Screenshot_20210607-120241](https://user-images.githubusercontent.com/57868975/121008180-fedd4a00-c792-11eb-9ff3-33ef47e75579.jpg)
_Input screenshot when trying to add a feature_

![Screenshot_20210607-120356](https://user-images.githubusercontent.com/57868975/121008189-01d83a80-c793-11eb-846b-d0bc8e012bb4.jpg)
_QField screenschot when preparing to add a feature_

**Comment by BoswachterMarc** [comment]
It works now 👍💪💚🌳

![Screenshot_20210607-173531](https://user-images.githubusercontent.com/57868975/121048486-1fb79680-c7b7-11eb-91f6-bc11f5576c6f.jpg)
![Screenshot_20210607-173543](https://user-images.githubusercontent.com/57868975/121048509-29d99500-c7b7-11eb-99a3-3f6d7063c9e0.jpg)

**Comment by saberraz** [comment]
Did you change something in the form? Would be great if you describe your work-around.

**Comment by BoswachterMarc** [comment]
I thought you guys where the work-around... I have no idea 🤔

**Comment by chris9404** [comment]
2 Workarounds:
1. Organize the container as in the image below:
![ContainerGroups](https://user-images.githubusercontent.com/85164641/121320537-8d75d680-c90d-11eb-89fd-d94f9062c651.jpg)

2. If from above you don't want containers within containers, untick "Show as group box" and the containers will show up as tabs in the app, based on Expression: 
![ContainerGroupsAlt](https://user-images.githubusercontent.com/85164641/121321600-88655700-c90e-11eb-882e-d2a5ec420862.jpg)

**Comment by PeterPetrik** [comment]
related https://github.com/MerginMaps/input/issues/1458

**Comment by PeterPetrik** [comment]
> It works now 👍💪💚🌳

shall we close it in that case?
