### ISSUE TITLE
Add leading slash to APIs in MerginAPI to allow custom servers

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#1470]
Some of the APIs in Input does not start with slash. E.g.:

`v1/auth...` this is a problem when user uses a custom server and do not add slash in the end like `https://public.cloudmergin.com` instead of `https://public.cloudmergin.com/`.

Without the slash in the end of server address, API call would be like `https:://public.cloudmergin.comv1/auth` which results in invalid request and user is not able to log in / register, ..

**Comment by wonder-sk** [comment]
Also worth checking whether the URL starts with https:// or http:// - and if not, maybe we should automatically prepend https:// 

See https://github.com/lutraconsulting/mergin/issues/8 for an instance of such issue.
