### ISSUE TITLE
Value Relation Widget: Order by Value not working

### ISSUE THREAD

**Issue by chris9404** [MerginMaps/mobile#1482]
When the Order by Value option is ticked within the widget settings, the list of options are sorted in QGIS, but within input it is not sorted. Example below:
![SortingIssue](https://user-images.githubusercontent.com/85164641/122023588-fd7dd400-cdc7-11eb-95f5-0e0a4ce7ff56.jpg)

**Comment by Uffeshub** [comment]
This is still a issue. Any news on this one?
