### ISSUE TITLE
Keep fields with "Apply default value on update" as editable.

### ISSUE THREAD

**Issue by chris9404** [MerginMaps/mobile#1483]
I have a "prefix matching" expression which checks a field's current value against another field's value, and updates it if there isn't a substring match (e.g. "block_id"s value changes, then "tree_name"s value should change as well).
This is done with the form expression in the Default value, and "Apply default value on update" ticked.

The problem is that in Input the field ("tree_name") is not editable, although in QGIS it is editable and works as intended.

Expression:
if ("tree_name" IS NULL, 
        "block_id", 
        if (substr("tree_name", 0, length("block_id")) != "block_id", --check that the prefix of the field is equal to the block_id
            "block_id", -- if the condition finds descrepancy (caused by user input or block_id selection change), change to block_id
            "tree_name") -- else keep it the same

**Comment by saberraz** [comment]
Hi @chris9404 do you have an example project to reproduce this issue?

**Comment by chris9404** [comment]
> Hi @chris9404 do you have an example project to reproduce this issue?

@saberraz Can I give you access to a project on mergin?

**Comment by saberraz** [comment]
Sure. My username is saber

**Comment by chris9404** [comment]
I have given you access. This example is unfortunately different to what I described above, but it's the same issue.

Record a new point under the map theme "Field Note". The very first field is "Farm Name". From that dropdown select Future Farm Unit 1.
Go to the next tab ("Block Note and Action") -> Field "Block Name" has a dropdown that works in QGIS, but not in input. The dropdown is greyed out.

**Comment by tomasMizera** [comment]
Fields with "Apply default value on update" are intentionally disabled for now
