### ISSUE TITLE
Android - dark theme issues

### ISSUE THREAD

**Issue by dracic** [MerginMaps/mobile#1535]
When using dark theme on Android, text in messageboxes (for example deleting projects) is not visible. I don't see any hurry to support dark theme, but at least system dialogues should work.

<img src="https://user-images.githubusercontent.com/4533263/124395255-596eb500-dd03-11eb-874a-337b3f7c6165.png" width="600" >

**Comment by PeterPetrik** [comment]
@jozef-budac can you test with 2024.1 RC?

**Comment by jozef-budac** [comment]
On the current RC, all notification looks OK in dark mode on Android
