### ISSUE TITLE
Custom mergin URL has bad UX

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/mobile#1544]
Right now, the setup of custom mergin URL can be slightly confusing:
- it does not work if http:// or https:// prefix is missing
- it does not work if final slash is missing (#1470)
- it is necessary to click the pencil icon again to confirm the URL
- if the URL is longer, one may need to switch to landscape mode just to be able to confirm it

See https://github.com/lutraconsulting/mergin/issues/8

**Comment by tomasMizera** [comment]
Fixed in the redesigned app
