### ISSUE TITLE
Attachments: config option to avoid copying files to project folder

### ISSUE THREAD

**Issue by Brent-Edwards** [MerginMaps/mobile#1631]
I've tested various form settings and configurations and I am unable to get this to work consistently.

It seems to work fine when editing and adding an attachment from a PC (path only, no file copied to Mergin), but it always copies the photo to Mergin when editing/attaching from iOS or Android.

Also, it only seems possible to attach photos from iOS and Android - I can open a separate issue if desired.

Thanks!

**Comment by wonder-sk** [comment]
> It seems to work fine when editing and adding an attachment from a PC (path only, no file copied to Mergin), but it always copies the photo to Mergin when editing/attaching from iOS or Android.

It is not clear to me what you are trying to achieve. Could you please describe your use case in more detail, what do you expect and what happens instead?

> Also, it only seems possible to attach photos from iOS and Android - I can open a separate issue if desired.

Sorry I am a bit lost on this comment - iOS and Android are the two platforms supported by Input - where else should it be possible to attach photos?

**Comment by Brent-Edwards** [comment]
> > It seems to work fine when editing and adding an attachment from a PC (path only, no file copied to Mergin), but it always copies the photo to Mergin when editing/attaching from iOS or Android.
> 
> It is not clear to me what you are trying to achieve. Could you please describe your use case in more detail, what do you expect and what happens instead?

I would like to be able to select a file (photo or other file type) through the file manager interface and save only the path/hyperlink to the file in the desired GPKG field without copying the file and having it synced through Mergin. Is that clear?

> 
> > Also, it only seems possible to attach photos from iOS and Android - I can open a separate issue if desired.
> 
> Sorry I am a bit lost on this comment - iOS and Android are the two platforms supported by Input - where else should it be possible to attach photos?

Two icons are presented on the "Edit Feature" form in iOS/Android - "Take a photo" and "From gallery":

    ![image](https://user-images.githubusercontent.com/13538726/133606005-a2f58d54-f83b-4377-b148-816966feea41.png)

When editing the same layer of the same project in QGIS on a PC, the standard Windows file manager appears allowing the user to select **_any type of file, not just photos_**:

    ![image](https://user-images.githubusercontent.com/13538726/133607090-44d5b3b2-0712-4251-8d80-ac3fd156abba.png)

Please let me know if require further clarification.

Thanks!

**Comment by wonder-sk** [comment]
> I would like to be able to select a file (photo or other file type) through the file manager interface and save only the path/hyperlink to the file in the desired GPKG field without copying the file and having it synced through Mergin. Is that clear?

Okay I see. But what is the actual use case? Suppose that would work and you pick a picture somewhere in your mobile device, and you would get a path like `/storage/emulated/0/Pictures/my-picture.jpg` saved in your feature - how would you make use of it? If the picture does not get copied to the project directory and uploaded to Mergin, you won't be able to use it later in the office...?

Regarding support for other types of files apart from pictures, that's currently not supported in Input - there's already a feature request for that - #862

**Comment by Brent-Edwards** [comment]
> > I would like to be able to select a file (photo or other file type) through the file manager interface and save only the path/hyperlink to the file in the desired GPKG field without copying the file and having it synced through Mergin. Is that clear?
> 
> Okay I see. But what is the actual use case? Suppose that would work and you pick a picture somewhere in your mobile device, and you would get a path like `/storage/emulated/0/Pictures/my-picture.jpg` saved in your feature - how would you make use of it? If the picture does not get copied to the project directory and uploaded to Mergin, you won't be able to use it later in the office...?
> 

By allowing the option to save the file path and/or the file, the user would be able choose whether or not to sync the attached files, thus reducing network load with large/numerous files. On Android, it's easy enough to copy photos back at the office to the desired location without having to sync them back and forth unnecessarily over a network connection.

> Regarding support for other types of files apart from pictures, that's currently not supported in Input - there's already a feature request for that - #862

**Comment by wonder-sk** [comment]
> By allowing the option to save the file path and/or the file, the user would be able choose whether or not to sync the attached files, thus reducing network load with large/numerous files.

How do you foresee this would work - whenever you pick a file (photo), you would be asked afterwards whether to copy the file to the project or to keep it where it is? Or it would be pre-configured in the project and either always or never copy? The issue with the former option is that it would complicate the GUI for the most common case... We are trying hard to keep the app as simple as possible, so that it "just works".

> On Android, it's easy enough to copy photos back at the office to the desired location without having to sync them back and forth unnecessarily over a network connection.

Well... it is easy if there is a single person doing the survey, but with a team of surveyors at some other location, that is not so easy, and using cable to copy pictures around can be error-prone (from our experience). To save the bandwidth, we have recently added an option to do selective sync in Input (#911) - if enabled, Input would only upload newly captured photos, but not download new photos from others.

**Comment by Brent-Edwards** [comment]
> > By allowing the option to save the file path and/or the file, the user would be able choose whether or not to sync the attached files, thus reducing network load with large/numerous files.
> 
> How do you foresee this would work - whenever you pick a file (photo), you would be asked afterwards whether to copy the file to the project or to keep it where it is? Or it would be pre-configured in the project and either always or never copy? The issue with the former option is that it would complicate the GUI for the most common case... We are trying hard to keep the app as simple as possible, so that it "just works".
> 

Either option could be justified. For the sake of simplicity, the pre-configured option would be the way to go. For the sake of flexibility, an option could be presented when attaching the file. Perhaps a hybrid approach, pre-configured/default option and then the possibility to override when attaching the file.

> > On Android, it's easy enough to copy photos back at the office to the desired location without having to sync them back and forth unnecessarily over a network connection.
> 
> Well... it is easy if there is a single person doing the survey, but with a team of surveyors at some other location, that is not so easy, and using cable to copy pictures around can be error-prone (from our experience). To save the bandwidth, we have recently added an option to do selective sync in Input (#911) - if enabled, Input would only upload newly captured photos, but not download new photos from others.

Point taken for the team of surveyors. Other scenarios could be envisioned where the team allows the photos to sync through another service/app (ex. Google Photos account) and then points the links to desired location (ex. virtual field `'\\path\to\photos\' || regexp_substr("column_with_full_path", '([^/]+$)')`). Perhaps I've been lucky, but I've never experienced errors when copying files with a cable. That's great news for the selective sync option - I'll be sure to check that out.

Thanks!

**Comment by wonder-sk** [comment]
> Either option could be justified. For the sake of simplicity, the pre-configured option would be the way to go. For the sake of flexibility, an option could be presented when attaching the file. Perhaps a hybrid approach, pre-configured/default option and then the possibility to override when attaching the file.

Indeed that could work to support advanced workflows, while keeping the default workflow simple.

> Other scenarios could be envisioned where the team allows the photos to sync through another service/app (ex. Google Photos account) and then points the links to desired location

This is actually something we have been thinking about already - to have a tool (similar to mergin-db-sync) to push pictures from Mergin projects to 3rd party services such as Dropbox, Google Drive, Sharepoint etc. But currently there are no concrete plans how/when to do that...

**Comment by Brent-Edwards** [comment]
> > Either option could be justified. For the sake of simplicity, the pre-configured option would be the way to go. For the sake of flexibility, an option could be presented when attaching the file. Perhaps a hybrid approach, pre-configured/default option and then the possibility to override when attaching the file.
> 
> Indeed that could work to support advanced workflows, while keeping the default workflow simple.
> 
> > Other scenarios could be envisioned where the team allows the photos to sync through another service/app (ex. Google Photos account) and then points the links to desired location
> 
> This is actually something we have been thinking about already - to have a tool (similar to mergin-db-sync) to push pictures from Mergin projects to 3rd party services such as Dropbox, Google Drive, Sharepoint etc. But currently there are no concrete plans how/when to do that...

Thanks for the response. Keep up the good work with Input/Mergin!

**Comment by tomasMizera** [comment]
Hello @Brent-Edwards, I just discovered this old thread. We have already implemented the solution to store photos in 3rd party service - e.g. AWS S3. Please check out https://github.com/MerginMaps/media-sync
