### ISSUE TITLE
UI/UX issue with capturing lines/polygons

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#1642]
When adding polylines it's hard to determine if the pervious vertex was recorded, sometimes the segment goes red, sometimes not. When you start a polyline there is a grey dot. But not for other vertices. Some consistency and bright color would help with this.

**Comment by jozef-budac** [comment]
related to https://github.com/lutraconsulting/input/issues/1433

**Comment by tomasMizera** [comment]
Hopefully sorted now :)
