### ISSUE TITLE
Field validation failed for QR code field

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#1683]
When recording numeric field with QR code, I am able to insert text into it and save. 
It looks like the problem is only on android phones

you can use project tc04_qrcode to test this. 

https://user-images.githubusercontent.com/83582181/135824574-fbe6d398-a982-426d-89af-4cbfad02706d.mp4

**Comment by tomasMizera** [comment]
@jozef-budac can you still reproduce this one?

**Comment by jozef-budac** [comment]
yes, you can still insert text into numeric field

**Comment by tomasMizera** [comment]
That is expected, but it should show a text "Invalid number" or something like that and not let you save the form. Is it working like this?

**Comment by jozef-budac** [comment]
In the manual test there is this requirement:

**Comment by jozef-budac** [comment]
The problem is, that the validation error appears only for a 0.5s and and user is able to save non numeric value into numeric QR code field. After save, the value in the field is 0, but user will believe, scanned value was stored.

**Comment by jozef-budac** [comment]
Still valid bug in 1.9.0

**Comment by ValentinBuira** [comment]
Can't reproduce in latest master

I'm able to read text in a numeric field using qr code but the field validation works as excepted with the error "Value must be a number"

Feel free to reopen if it's still not working for you

**Comment by jozef-budac** [comment]
Verified on 2023.3.1 RC
