### ISSUE TITLE
Wrong compass direction

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#1707]
This is only reported in iOS. The direction does not line up with other apps (e.g. Google maps).

**Comment by saberraz** [comment]
@jozef-budac it would be a good idea to have a manual test for this (if there is not one already).

**Comment by saberraz** [comment]
It looks like it is 180 degrees rotation:
![IMG_1530](https://user-images.githubusercontent.com/2649047/137356311-13a73f00-d100-4ddb-b0a4-59b27286205d.jpg)

**Comment by tomasMizera** [comment]
Duplicate of https://github.com/MerginMaps/mobile/issues/3074
