### ISSUE TITLE
Project name validation for Project Wizard

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#1715]
Currently, users can create a project which would not be valid for Mergin upload (e.g. containing &, %, etc) in project Wizard.

We should do the same validation for project upload during Project Wizard and not display the illegal characters which cannot be used in the project name. If those characters are present, Create project will remain inactive/greyed out.

To reproduce the issue:
- Run project wizard
- Create a project with a special character (e.g. test&test)
- Try to upload it to Mergin: it will warn user the project contains special characters...if user had already collected data...this is too late!

**Comment by jozef-budac** [comment]
Fixed by https://github.com/MerginMaps/input/pull/2449
