### ISSUE TITLE
Child layer's relation field must be present in form otherwise relation won't be saved in Input

### ISSUE THREAD

**Issue by Koivusto** [MerginMaps/mobile#1764]
I'm trying to hide foreign key fields from my layers in Input. User is supposed to access child features via parent feature form. I've been unsuccessful for now and I'm not sure if this is a bug or if I am missing something. 

I've created an example project. In it I've created two layers, one parent and one child. Relation is set in QGIS and it is 1:N. I have a simple form setup and depending on if I have the child table's field containing the parent key in the form or not, Input fails to assign relation value to said field. 

An example of excluding the field in child table form (Input doesn't work):
![form setup input fails](https://user-images.githubusercontent.com/24698263/143062805-11713fc3-0f23-42cd-ac38-6541eb89b937.png)

An example of including the field in child table form (Input works):
![form setup input works](https://user-images.githubusercontent.com/24698263/143062826-c72f390b-c92b-4eba-a962-00818018946a.png)

It is important to note that I'm accessing child table form through existing parent feature. In QGIS this happens with identify tool. In Input I  press the parent feature and access the second tab in form. 

I have an example project Ubiguville/relation_bug which is public.

**Comment by PeterPetrik** [comment]
This may have been fixed by https://github.com/MerginMaps/input/commit/0ba2a711b34867f203a93dc913e6d95bbe5db7d4

**Comment by PeterPetrik** [comment]
Current status (v2.3.0)
- it is possible to assign "hidden" widget in parent form for `unique_id`
- when you delete relation widget in child feature, the saved feature does not have stored reference to parent layer

test project:
[Bug1761](https://app.merginmaps.com/projects/peter.petrik/Bug1761)

**Comment by tomasMizera** [comment]
Yep, should be fixed already
