### ISSUE TITLE
Wrong warning when deleting a sync project

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#1766]
When I try to delete a synced project a warning message pops up:
`Any unsynchronized changes will be lost`

If the project has been already synced and there is no unsynced changes the error message should not appear. There are two cases:

- The project is already synced and the data are on the server, we can just delete the project. No need for warning
- The project is not uploaded or not synced, the message should appear.

**Comment by PeterPetrik** [comment]
There are new texts in 2024.1.0
