### ISSUE TITLE
Preview panel detail not working as expected

### ISSUE THREAD

**Issue by mostlyAtNight** [MerginMaps/mobile#1796]
When I set up my preview panel as follows:

![image](https://user-images.githubusercontent.com/884954/144995454-1e206bf9-6dda-404d-bf62-3e79632af798.png)

The result in Input is:

- Speces shown in title (good)
- Only species shown in details below (not good)

A **brief** investigation looks like only the last entry in html map tip is shown.

See this project for details:  https://public.cloudmergin.com/projects/Pete/trees-and-hedges/tree

**Comment by PeterPetrik** [comment]
Wondering if it happens if you remove whitespace at the end of lines?

**Comment by qnmai** [comment]
Same issue on Samsung Galaxy Tab Active3, SM-T575, Android 11, with Input v1.4.0

`# fields
designation
etat_pot`

This only shows etat_pot.

`# fields
designation`

This shows designation fine.

Example project:
https://public.cloudmergin.com/projects/SPEED/SIG_SPL_TAHAA_220502/tree

**Comment by tomasMizera** [comment]
Can't reproduce it anymore, feel free to reopen
