### ISSUE TITLE
Text overlap buttons in settings

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#1803]
In master, if there is long string in settings, it overlaps the controls. 
Expected is, that text is shortened or put to two lines so it doesn't overlap the controls

![5_2](https://user-images.githubusercontent.com/83582181/145185221-ee291c06-561c-4388-b280-0bee9f8b7e0b.png)

**Comment by PeterPetrik** [comment]
related to #1833 ?

**Comment by jozef-budac** [comment]
Related to https://github.com/MerginMaps/input/issues/1355

**Comment by PeterPetrik** [comment]
fixed in 2024.1
