### ISSUE TITLE
Warning banner needs some more tweaking

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#1857]
The layout in the waning layers looks a little bit strange. 
So probably it can be fixed, when detailed page for this warning will be changes also

https://files.slack.com/files-pri/TBXE5PUU9-F02QYE28P0W/screenshot_20211217-102908.png

**Comment by PeterPetrik** [comment]
screenshot not available and referenced app is very old, closing

**Comment by jozef-budac** [comment]
![image](https://github.com/MerginMaps/input/assets/83582181/d3ad9d85-dee4-4cf7-abd6-7c64ca6f5722)
Screenshot from latest code

**Comment by PeterPetrik** [comment]
reimplemented from scratch in 2024.1
