### ISSUE TITLE
Translate standard buttons

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#2024]
Buttons in QML dialogs are not translated by default, we need to find a way how to translate them.

Example:
<img src="https://user-images.githubusercontent.com/22449698/161216131-92a099ae-0e5f-4b97-82c9-d6c02672661f.jpeg" width=300>

See https://forum.qt.io/topic/54182/can-not-translate-standardbuttons-is-this-expected/6

**Comment by PeterPetrik** [comment]
we do not use these dialogs in 2024.1.0
