### ISSUE TITLE
Preview panel for # fields doesn't work on android

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#2028]
Our custom preview panel for # fields variables doesn't work well on android. 

https://user-images.githubusercontent.com/83582181/161539199-118a5c9f-4faa-49d9-9831-c592a3207f21.mp4

Expected result it this:

![image](https://user-images.githubusercontent.com/83582181/161539311-9d5bf139-3db8-44e1-a26f-5a4b1e9d08eb.png)

**Comment by jozef-budac** [comment]
This issue appears on latest RC on Xiaomi Redmi Note 8T. I was not able to simulate it on iOS. Also Tomas was not able to simulate this on his Android device.
When I download project I can see the fields are displayed in the preview panel. When I go trough other features, the fields preview panel become empty. 
Opening other project fixed this temporary, as after some time (during which I open different features), field preview panel is empty again.

https://user-images.githubusercontent.com/83582181/161544079-54d8b0bc-923b-4946-bc52-681f4db2e7be.mp4

**Comment by PatrikMizera** [comment]
I tested it also and it works fine for me. Tested on Xiaomi Redmi Note 10S, 64.

**Comment by PeterPetrik** [comment]
related to https://github.com/lutraconsulting/input/issues/1796

**Comment by tomasMizera** [comment]
Completely rewritten, feel free to reopen if needed
