### ISSUE TITLE
Enfore Null Constraint does not work for attachment fields

### ISSUE THREAD

**Issue by coenEcorys** [MerginMaps/mobile#2056]
In QGIS, we've created a field in the attribute table with the widget type 'attachtment'. The field is empty but it should be mandatory to take a picture, so we enforced the Not Null constraint. It is still possible however, to not take a picture in Mergin and submit the feature.

**Comment by VitorVieiraZ** [comment]
Tests conducted successfully following the problem description, issue has been resolved.

**Comment by jozef-budac** [comment]
Verified on 2024.1.1
