### ISSUE TITLE
Wrong number of children in 1-n relations

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#2060]
I noted a strange behaviour when adding observations to a one-to-many demo project. Each time I add an observation (without saving) the displayed observation count increases by an unusual amount and does not display the correct number of observations. Once I click save and click on the feature to add more observations the count is correctly displayed.

https://user-images.githubusercontent.com/2649047/165350289-583ed3e6-970c-43d8-b1d2-60883ef58975.mp4

**Comment by tomasMizera** [comment]
Is this still happening @saberraz?
