### ISSUE TITLE
Read-only layers and available edit controls

### ISSUE THREAD

**Issue by dracic** [MerginMaps/mobile#2106]
Currently read-only layers have edit, delete and edit geometry (points only) controls enabled. You cannot save changes, but they should be disabled like editable polygons and lines have disabled edit geometry button.

**Comment by ztgis** [comment]
I can reproduce this issue with the following steps:

1. Identify a feature
2. Tap on the description (HTML formatted text)
3. Feature attributes appear with "Edit" button at the bottom (Edit button should be deactivated or invisible)
4. Further, modifying the attributes is possible, but the "Save" button does nothing (button should be deactivated)

**Comment by tomasMizera** [comment]
Good points, thanks @dracic and @ztgis for reproducing steps!
