### ISSUE TITLE
With multiple photos, move the "add photo" button to the left to avoid scrolling across a long list of thumbnails

### ISSUE THREAD

**Issue by GeoSpark** [MerginMaps/mobile#2123]
If a feature can have multiple photos added to it, the form should keep the "add photo" button to the left of the list of thumbnails so the user doesn't have to scroll through all the photos to be able to add a new one.

**Comment by saberraz** [comment]
Just to be clear, here is the screenshot of the problem in 1-n relation for multiple photos
![image](https://user-images.githubusercontent.com/2649047/173775664-ccf0ab5b-9d02-412c-896c-fb9ad37585b9.png)

**Comment by tomasMizera** [comment]
The add button will be first in the upcoming version :)
