### ISSUE TITLE
App font is small and does not scale on hi res display

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#2158]
The fonts appear very small and scaling the display through OS settings does not affect the app.

**Comment by tomasMizera** [comment]
What is wrong with the attached picture @jozef-budac ?

**Comment by tomasMizera** [comment]
@saberraz have you tried to restart the app after changing the scale?

**Comment by tomasMizera** [comment]
App needs to be restarted in order to load the new scale

**Comment by PeterPetrik** [comment]
fixed by https://github.com/MerginMaps/mobile/pull/3200
