### ISSUE TITLE
Wrong storage indicator

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#2167]
The app always shows 2GB/ 2GB storage even if I have 25 GB storage and only using a different amount:
![image](https://user-images.githubusercontent.com/2649047/179926993-7bca2b70-419f-4285-ab0b-b2f870bbc21c.png)

**Comment by tomasMizera** [comment]
This seems to be a server issue. This is my storage:
<img width="227" alt="image" src="https://user-images.githubusercontent.com/22449698/179942736-564b5fee-f197-4027-990a-6f23414c7cce.png">

This is returned from server API:
<img width="267" alt="image" src="https://user-images.githubusercontent.com/22449698/179943074-0c4866d9-e6c2-4a70-aa71-6b2e4ab17440.png">

`storage` and `storage_limit` have the same value. We use these to show the `Using x GB / y GB` text, where `x` is `storage` and `y` is `storage_limit`.

@saberraz  Can you transfer this issue to the server, please?

**Comment by saberraz** [comment]
Thanks @tomasMizera I have opened a new ticket and keep this one open for future reference to users.

**Comment by PeterPetrik** [comment]
Is this solved?

**Comment by tomasMizera** [comment]
> Is this solved?

Yes, this should be solved since server 2024.1.0
