### ISSUE TITLE
Split geometry visual problems

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#2320]
There are a few problems with the split geometry in the latest version:

1. No (or sometimes wrong-coloured) guideline (❌)
2. ~~Floating `Back` button is there (correct ✅), but has no action (❌)~~
3. ~~`Cancel` button is there, even though it should not be there anymore (❌)~~

<img width="400" alt="Screenshot 2022-10-06 at 15 05 40" src="https://user-images.githubusercontent.com/22449698/194320334-fea1ea81-ca32-49eb-b51b-d0961287d1ce.png">

**Comment by tomasMizera** [comment]
The only relevant thing now is the first point - no guideline

**Comment by ValentinBuira** [comment]
I could not reproduce the part the wrong colored guideline, let me know if the issue still happen

**Comment by tomasMizera** [comment]
> I could not reproduce the part with the wrong colored guideline, let me know if the issue still happen

That one is most likely not happening anymore @ValentinBuira
