### ISSUE TITLE
Keyboard remains open after form edit cancel

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#2324]
Scenario:
1)  record a feature and hit done
2) form will appear, insert same data to some field (keep keyboard opened) 
3) Now hit cancel -- keyboard remains opened even on the map

Expectation is that keyboard will be closed after user hit Cancel button

**Comment by erpas** [comment]
A user report:
our Iphone users of the Mergin Maps app are having an issue with the virtual keyboard not disappearing after they’ve entered a data point (intermittent), they have to close/reopen the app to rectify.

Not experiencing the issue at all on our android tablets.

**Comment by tomasMizera** [comment]
Should be sorted out now
