### ISSUE TITLE
iOS input app crashes when opening project

### ISSUE THREAD

**Issue by tdubbeldam** [MerginMaps/mobile#2326]
Hi,

I can make a new project on my mobile device without any problem, but when I try open a project I've downloaded from my cloud storage the app **immediately** **crashes**. No warning or error shown. 

From a colleague who works on an android device I've understood that he is able to open the same project but he is shown a warning that there are problems loading the project. I am not sure however what they are as I am unable to use his device and don't receive any on my personal device. Therefore I am not able to fix them either.

Cheers,

Tim

**Comment by saberraz** [comment]
Hi Tim,
Could you share the project with **support** user? Also could you make sure you are using the latest version of the app?

**Comment by tdubbeldam** [comment]
I have invited the support user with the permissions 'reader'. I am using the most recent version available on iOS (v1.8.0)

**Comment by saberraz** [comment]
Hi Tim, the issue seems to be related to: #1959 
Also you have several missing layers.

**Comment by tdubbeldam** [comment]
Okay, I noticed that too when i looked in my mergin account. How can I fix it though?

**Comment by saberraz** [comment]
I think in this might have been resolved due to the update to the new SDK.

Alternatively, make a local copy of the WFS and use it as a GeoPackage.

**Comment by tomasMizera** [comment]
Please reopen this ticket if it is not solved yet.
