### ISSUE TITLE
Done button does not close the keyboard

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#2444]
Upstream Qt bug: https://bugreports.qt.io/browse/QTBUG-109202

**Comment by tomasMizera** [comment]
Fix will be included in 6.5.0

**Comment by PeterPetrik** [comment]
Can we try with https://github.com/MerginMaps/input/tree/dev-2.3 @jozef-budac it should be fixed in Qt 6.5.x?

**Comment by jozef-budac** [comment]
The bug is fixed in Qt 6.5.x
