### ISSUE TITLE
Direction indicator shows wrong direction

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#2468]
The direction indicator change direction quite randomly. But it happens in past also. So not sure if QT do any change there. 
But there is quite different between direction indication in Google maps and out app

In  the app I change direction this way north -> west -> south -> east -> north.
In google maps It works quite well
In our app it looks quite random movements

https://drive.google.com/file/d/1xnAirIFWzjF-LRdXQWFC_2DSCQtbzgU2/view?usp=sharing

**Comment by tomasMizera** [comment]
Can you check if you have your compass calibrated? I remember having issues with these outside

**Comment by jozef-budac** [comment]
But in this case should not be the problem visible in both google maps and input? I can try to calibrate it

**Comment by jozef-budac** [comment]
I downloaded compass app and it shows direction quite precisely. Input is still quite random
https://drive.google.com/file/d/1BjcTRDMewdOfO3ZOkO3v3hWEx1ZWg62d/view?usp=sharing

**Comment by jozef-budac** [comment]
Probably duplicate of https://github.com/MerginMaps/input/issues/1707
