### ISSUE TITLE
Input shuts down when opening specific project on iOS

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/mobile#2493]
Patrik M. has access to this project 

When the project is opening, the app will crash without any error 

https://user-images.githubusercontent.com/94351263/212004770-86a08834-0131-4a13-828c-10923b3cfcf1.MP4

**Comment by erpas** [comment]
The app crashes when panning/zooming the map with projects mentioned in the support ticket:
https://support.lutraconsulting.co.uk/a/tickets/3380

**Comment by tomasMizera** [comment]
Is this still happening @erpas? Do we have more info here?

**Comment by VitorVieiraZ** [comment]
Hello @PatrikMizera, could you please share this project with me? (My account is vitor.vieira@lutraconsulting.co.uk). 
I was able to reproduce the issue in related projects while the app was under significant stress.

**Comment by VitorVieiraZ** [comment]
This issue can no longer be reproduced. However, the relationship between WFS layers and iOS still needs further review.
