### ISSUE TITLE
iOS camera crash on destruction in Qt6

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#2495]
QML Camera in iOS crashes when the camera is closed.
Will hopefully be fixed in Qt6.5

https://github.com/MerginMaps/input/pull/2380 Attempts to work this around but it is still there.

See https://bugreports.qt.io/browse/QTBUG-110131

**Comment by jozef-budac** [comment]
On 23.06.433511 build I tried to capture a photo and the app didn't crash. So I believe this issue is not present in QT6.5.x

**Comment by tomasMizera** [comment]
We can not really close this one. The app currently uses a work-around. We need to get rid of the workaround and try it with normal camera

**Comment by tomasMizera** [comment]
Fixed by #2917
