### ISSUE TITLE
iOS renders bigger components / fonts compared to Android

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#2528]
I am not sure if this changed when we moved to Qt6, but it seems that everything (especially fonts) looks bigger on iOS, compared to Android. 
This issue makes it hard to find a proper design, as something that looks just about ok on 🤖 , looks terrible on 🍏  and vice versa.

> Note: screens on these phones are not identical - Android is taller. Despite that, I would expect to see fonts/components of the roughly same size - the phone with Android should only show more content vertically.

Here are several examples:

<table>
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>

  <tr>
    <td><img src="https://user-images.githubusercontent.com/22449698/215356736-2b19e439-c103-40c9-beec-dccea38f417a.jpg" width="300"/></td>
    <td><img src="https://user-images.githubusercontent.com/22449698/215356737-a64b169b-5ee3-4485-8b98-4b3f1274a3bb.jpeg"  width="300"/></td>
  </tr>

  <tr>
    <td><img src="https://user-images.githubusercontent.com/22449698/215356744-08fd304b-58d3-407e-8a8e-fa025e3d5065.jpg" width="300"/></td>
    <td><img src="https://user-images.githubusercontent.com/22449698/215356755-746dcb00-ab46-4783-948d-65ead5d55130.jpeg"  width="300"/></td>
  </tr>

  <tr>
    <td><img src="https://user-images.githubusercontent.com/22449698/215356758-f718ea7a-6926-4cff-a08c-ca4fe8d740b9.jpg" width="300"/></td>
    <td><img src="https://user-images.githubusercontent.com/22449698/215356760-c507b1c0-52e3-49bb-8e5c-f5c1d49fed25.jpeg"  width="300"/></td>
  </tr>

  <tr>
    <td><img src="https://user-images.githubusercontent.com/22449698/215356761-6832663d-fd8e-4792-b8f2-f6d8d424250e.jpg" width="300"/></td>
    <td><img src="https://user-images.githubusercontent.com/22449698/215356762-c1d9f6de-90b4-4bf1-b5bf-fca213350572.jpeg"  width="300"/></td>
  </tr>

  <tr>
    <td><img src="https://user-images.githubusercontent.com/22449698/215356726-9156c882-62f3-4c04-ab85-26087543b231.jpg" width="300"/></td>
    <td><img src="https://user-images.githubusercontent.com/22449698/215356728-e8b53b12-33ab-4e80-acc6-3b713cbc3d4d.jpeg"  width="300"/></td>
  </tr>

 </table>

**Comment by PeterPetrik** [comment]
fixed by https://github.com/MerginMaps/mobile/pull/3200
