### ISSUE TITLE
Streaming mode is present for point features

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#2565]
Streaming recording is available also for point and multipoint features. I believe this is not intended.
Anyway, it didn't cause any harm as Done button records a point anyway.

Scenario:
1) hit record on point layer 
2) hit and hold GPS button -> you enter streaming mode

**Comment by gilles-morain** [comment]
Should have tested it first: currently it only keeps the last point, so useless and probably labeled ok as a bug!
