### ISSUE TITLE
Cursor on multiple lines in the form

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#2566]
Scenario:
1) download project https://app.merginmaps.com/projects/input-testing/tc05_forms_widgets/tree
2) hit record so form will open
3) fill all the field on "Text" tab
4) Switch to second tab "Number"
5) Hit cancel to close the form
6) Hit record again and switch to "Text" tab again
-> there is cursor on all the fields and on two of them is flickering

https://user-images.githubusercontent.com/83582181/220561507-13b0feb0-063e-4d58-a3e2-c86dd52c0055.mp4

**Comment by tomasMizera** [comment]
Heh, should not be happening anymore :)
