### ISSUE TITLE
Option for making layer editable in terms of adding new records but with forbidden removement of old records

### ISSUE THREAD

**Issue by Tadeo98** [MerginMaps/mobile#2585]
Suggestion by West Midlands Historic Building Trust client (FD ticket 1772).
If this option isn't already there, would it be possible to make a layer editable partially, where the surveyor is able to create new records but unable to delete old ones?
Use case: volunteers making new records sometimes mess up and delete existing records from list of historic buildings. Would be useful to forbid them from removing records.

**Comment by tomasMizera** [comment]
This is a part of flexible permissions request
