### ISSUE TITLE
Wrong data/time when using data/time widget

### ISSUE THREAD

**Issue by Tadeo98** [MerginMaps/mobile#2592]
Following documentation - https://merginmaps.com/docs/layer/settingup_forms/#date-and-time ...
- with now() function and Apply changes... checked - in app (Android) the date is filled (correct) followed by time 0:00:00 without any chance of editing it (calendar icon is grayed out)
- with now() function and Apply changes... unchecked - in app the date is filled (correct) followed by time 0:00:00, now tapping calendar icon works but the time that is filled in is UTC, not local
- without now() function and Apply changes... unchecked - in app after tapping calendar icon again the time in UTC is filled in, not the local one

Now similar issues are seen in QGIS itself when creating new features so maybe this isn't related to the app only.

**Comment by VitorVieiraZ** [comment]
- App fills data with correct local time.
- Expected behavior when `now()` and `Apply default value on update` checked: the field should not be editable.

**Comment by jozef-budac** [comment]
Verified on 2024.3.0 RC
