### ISSUE TITLE
Short range navigation (stake-out)

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#2611]
When I am in the short range navigation mode in stakout feature, there is a location button in the preview panel, which should center map on the navigation, but it does nothing. It works for long range navigation.

**Comment by tomasMizera** [comment]
Can you please add a screenshot which button is that?

**Comment by jozef-budac** [comment]
The GPS button next to 'X' button. This screenshot is for long range navigation, but the same button have short range navigation, and in this short range navigation, the button doesn't work.

![obrázok](https://user-images.githubusercontent.com/83582181/223095753-b35a2bdc-b230-4e7d-bec0-cc32a9fa3a58.png)

**Comment by tomasMizera** [comment]
Should work now
