### ISSUE TITLE
Redraw geometry - redirected to GPS accuracy 

### ISSUE THREAD

**Issue by alex-cit** [MerginMaps/mobile#2638]
- Select a polygon and go to Redraw geometry
- Tap "Back"
Sometimes it goes "back" as expected. However, sometimes I get redirected to docs page about [GPS accuracy](https://merginmaps.com/docs/field/gps_accuracy/) 

https://user-images.githubusercontent.com/94905350/225705826-43d6c207-d370-4c7f-8551-6cc43b435119.mp4

Mergin Maps Input v2.1.0

**Comment by zezzagio** [comment]
Possibly related to #2705 and #2617 (#

It happens to me too sometimes, in the #2705 scenario. As exposed from stevenjh in #2617, all this behaviors seem to be related to different buttons mapping the same screen spaces.

**Comment by tomasMizera** [comment]
Should not be happening anymore
