### ISSUE TITLE
Distance interval in streaming mode not working.

### ISSUE THREAD

**Issue by Tadeo98** [MerginMaps/mobile#2691]
I tested project with both time and distance (1, 5, 10 m) intervals and it seems there is no difference.
Note: I was using only mobile's GPS with 3-4 m accuracy, perhaps that's a thing. Some users reported they got it to work after switching between these interval types back n forth and also after getting better coverage.

**Comment by PeterPetrik** [comment]
@jozef-budac this one works, no?

**Comment by jozef-budac** [comment]
The distance between two points corespond with the settings. I tried multiple distances in the settings and the distance between two recorded points changes with it.

There are two questions I have about it
1) probably maximum 2 or 3 points can be recorded in one second. If the distance traveled by the device is longer than 3x distance in the settings, the distance between two points would be probably higher then set in settings.

2) from the screenshot you can see that (at least visually) the distances between the points are different, even then the same distance was set im the settings (30m). But I am not sure map projections are responsible for this
![Screenshot_20240509_110318](https://github.com/MerginMaps/mobile/assets/83582181/266079f5-1aa7-4798-a431-1d3f45db65c2)

**Comment by tomasMizera** [comment]
> The distance between the two points corresponds with the settings. I tried multiple distances in the settings and the distance between two recorded points changed with it.
> 
> There are two questions I have about it
> 
>     1. probably a maximum of 2 or 3 points can be recorded in one second. If the distance traveled by the device is longer than 3x the distance in the settings, the distance between two points would be probably higher than set in the settings.
> 
>     2. from the screenshot you can see that (at least visually) the distances between the points are different, even then the same distance was set in the settings (30m). But I am not sure map projections are responsible for this
>        ![Screenshot_20240509_110318](https://private-user-images.githubusercontent.com/83582181/329192654-266079f5-1aa7-4798-a431-1d3f45db65c2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjQxNDUsIm5iZiI6MTcxNTMyMzg0NSwicGF0aCI6Ii84MzU4MjE4MS8zMjkxOTI2NTQtMjY2MDc5ZjUtMWFhNy00Nzk4LWE0MzEtMWQzZjQ1ZGI2NWMyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA2NTA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMDMyYzcwNzdjZDdkMTk1OWZhYTNlNGNkM2E2YTAxODkyNDkyNmRiZTc1OGFjM2NiNjJiODBhZDJjMzZlODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mJ2J6vaG3mTpbX9v7vP1021UUdz4zvGvDb6D3x1HMTY)

These are most likely issues with GPS signal jumps. If you have an accuracy of 2 meters, you can not expect to have nice 3m-long segments. It is calculated like this: once you get a new GPS position, it checks if it is more than X meters from the last point. But if the new position is a sudden jump of 5 meters, we add that point. Thus, I'd prefer to close this ticket

**Comment by jozef-budac** [comment]
I am ok with that, just for a note, I used 30m segments in the screenshot
