### ISSUE TITLE
Deleting an element from a child layer within the relation widget causes the application to delete the parent element instead

### ISSUE THREAD

**Issue by zezzagio** [MerginMaps/mobile#2705]
Possibly related to #2617

In the test project "project_relations":
1) add a new element in the "mainsub" relation widget (let say Name=SubSecond); save the element (tap "Save" in the top right corner of the form);
2) tap the "SubSecond" element; tap "Modify" then "Delete" (left bottom corner), then "ok" in the confirmation popup; the child element is correctly deleted;
3) tap the "SubFirst" element; then "Modify"; the app shows the map window as in #2617; never mind, tap "Back"; you are back in the mainsub form, it seems; tap "Delete", then "ok" in the confirmation popup;
4) the app shows the map window; the parent element has been deleted.

**Comment by tomasMizera** [comment]
We could not reproduce this anymore, most likely fixed when fixing #2617
