### ISSUE TITLE
Wrap long text for field names (or aliases)

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#2722]
When user has a very field name or field alias (cases when user wants to have a long question for the field name/alias for example), the text overflows on a small screen and does not wrap based on the screen size:
![image0](https://github.com/MerginMaps/input/assets/2649047/1d1a3a4b-a923-4c00-9401-6e4ee8aefe8f)

A similar issue related to field value is reported here: https://github.com/MerginMaps/input/issues/1720

**Comment by tomasMizera** [comment]
This is fixed in the new forms
