### ISSUE TITLE
Toggle gps centering when adding features

### ISSUE THREAD

**Issue by roya0045** [MerginMaps/mobile#2868]
When we try to add information in a project after we left the area, the auto-centering can lead to tedious amendments to a project.

Adding the option to disable/toggle auto-centering when adding features would be good and prevent a lot of redrawing and dragging about in some instances.

**Comment by tomasMizera** [comment]
Related to https://github.com/MerginMaps/input/pull/2614

**Comment by PeterPetrik** [comment]
as workaround maybe you can use https://f-droid.org/packages/cl.coders.faketraveler/ or https://play.google.com/store/apps/details?id=com.locationchanger&hl=en&gl=US for time being

**Comment by tomasMizera** [comment]
> as workaround maybe you can use https://f-droid.org/packages/cl.coders.faketraveler/ or https://play.google.com/store/apps/details?id=com.locationchanger&hl=en&gl=US for time being

Even better is to just turn off GPS altogether :)

**Comment by roya0045** [comment]
> as workaround maybe you can use https://f-droid.org/packages/cl.coders.faketraveler/ or https://play.google.com/store/apps/details?id=com.locationchanger&hl=en&gl=US for time being

Not quite an option on iOS. Though when possible I'll just do the changes in QGIS instead.

**Comment by tomasMizera** [comment]
This will be a part of the upcoming release :)

**Comment by roya0045** [comment]
> This will be a part of the upcoming release :)

Thanks for the confirmation!
