### ISSUE TITLE
Login screen disappearing logo

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#2889]
In the login screen, there is a difference in the page when the cursor is on the field and when it is not. 
Before the user hits the field, there is a text between the logo and the field. Then you hit it, and the text disappears.

Test steps:
1) open the app and go to the login screen -> see there is a text between the logo and the text fields
2) click on the field -> the text disappears 

https://github.com/MerginMaps/input/assets/83582181/40cb5a37-4a94-4011-8ab1-2c11262d7114

**Comment by PeterPetrik** [comment]
I have similar behaviour in v.2.4.0 iOS


https://github.com/MerginMaps/input/assets/804608/a069d0e6-a5e9-463a-b7c1-3a1d60401dfb

**Comment by tomasMizera** [comment]
It was like this for quite a lot of versions now. Will be handled by redesign
