### ISSUE TITLE
Cannot access About / version number unless user is logged in and has project open

### ISSUE THREAD

**Issue by volcan01010** [MerginMaps/mobile#2911]
### Summary

As a Mergin Input user, I would like a way to tell which version is running without having to be logged in with a project open, so that IT staff handling installed software can easily check it.

### Description

There are two locations where we can check the version number:

+ Settings > About
+ Settings > Diagnostic Log

However, the Settings menu is only visible when you are logged in with a project open.  It would be nice to be able to check this without having to do this.  Our particular use case is IT staff who are responsible for maintaining software across corporate laptops do the installation and need to be able to check that it has worked, yet they are not users of the software and do not have Mergin Maps accounts.

There are two potential solutions that would help us:

+ Print the Mergin Maps version number in the terminal log output that appears when you open it on Windows
+ Add a link to the About page (or the version number string) to the Login page

**Comment by tomasMizera** [comment]
Hello @volcan01010, thanks for your feedback, this is indeed an interesting point. 
`Settings > About` does not require you to be logged in though. You just need to have some projects downloaded. This is a suboptimal solution, but you can create a demo project on the device via the `create project` button in the project list.

**Comment by PeterPetrik** [comment]
Is this for mobile or desktop version? If desktop we may implement —version argument that will print version and not start gui at all ??

**Comment by volcan01010** [comment]
Yes, this is for the desktop version.

On Windows, when we start the application it opens two windows. One has the
gui, another shows log messages. The simplest solution would be to print
the version number as one of those messages.

Adding a `--version` flag would work, but would require training of our IT
staff to know that this was possible. Plus, when we use the app on Windows,
we normally launch it from the Start menu. To run it from the command line
on Windows would probably involve setting up system paths first, which is
another step to explain to the IT staff.

On balance, printing the version number in the start up logs (seems like
it) could be a simple way to solve the problem in our use case.

Thanks

**Comment by PeterPetrik** [comment]
Can you paste me here screenshot of terminal ?

**Comment by volcan01010** [comment]
Hi, here is a screenshot.  There are version numbers for QGIS and other libraries printed as the application starts and if the Input version was included, that would allow our IT staff to know which version they were working with.

![mergin_input_log_window](https://github.com/MerginMaps/mobile/assets/12040043/b937946e-962b-4918-a161-d31614ea4710)

On our systems, both the log window and the application window (behind) are displayed when the application is launched from the start menu.

**Comment by PeterPetrik** [comment]
@volcan01010 there should be Input version just before QGIS version in printout ; also the scrollbar is visible on the right on your screenshot? Are you sure you cannot scroll it up and that there are not input version printed? 
https://github.com/MerginMaps/mobile/blob/7c27b43132f51af4918ba1f8cca0d9fc708d91e6/app/main.cpp#L395

**Comment by volcan01010** [comment]
I don't have that on Windows.  The first message that I can see is the "Built with QGIS version" one.

**Comment by volcan01010** [comment]
(The gap above the top of the scroll bar in the screenshot turns into an up arrow, with the bar hard against it, when I move the mouse over)

**Comment by volcan01010** [comment]
Thanks @PeterPetrik!

**Comment by PeterPetrik** [comment]
You are welcome @volcan01010
