### ISSUE TITLE
Fix MerginAPI tests

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#2915]
There are common test failures in the auto tests within `testmerginapi`. 
Let's explore what the issue is and fix it :)

**Comment by PeterPetrik** [comment]
`server replied: UNPROCESSABLE ENTITY: Failed to push changes. Ask the project workspace owner to log in to their Mergin Maps dashboard for more information. (TrialExpired)\n”`

I pushed forward the trial expiration on the mobile app testing workspaces to Aug 2024

**Comment by PeterPetrik** [comment]
ok fixed adding working subsc. plan to test workspaces
