### ISSUE TITLE
Can't use string representation of 'true' and 'false' as default value for boolean field (mobile 2.5.0 and qgis 3.34.x)

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#2939]
With the project tc05_forms_derived, I can't save a feature with error "Saving failed"
In the diagnostic log I can see "Error occurred (position source)" ( tin1_input-ios-2.5.0_2023-12-04T10:18:46.682678.log)

Scenario:
1) open project tc05_forms_derived (on production)
2) fill the first tab with '11' in all fields to meet the constraints
3) Hit save -> you get an error.

This worked in all previous releases and APKs

![image](https://github.com/MerginMaps/mobile/assets/83582181/be9fef55-70f6-4618-8926-5837eb63c663)

![image](https://github.com/MerginMaps/mobile/assets/83582181/781f4b99-4171-4deb-b2f0-541536ba9ffa)

**Comment by PeterPetrik** [comment]
Error in console 
`2023-12-05 09:04:25.058221+0100 Input[2593:32260] "2023-12-05T08:04:25.058Z CommitChanges: Failed to commit changes:\nERROR: 1 feature(s) not added.\n\n  Provider errors:\n    wrong data type for attribute 12 of feature -2: 10\n"`

comes from new code in QGIS 3.34.0 where the type checking is more strict now:
https://github.com/qgis/QGIS/pull/54905

**Comment by PeterPetrik** [comment]
works with 
`if("chf2" = True ,False, True)`

fails with 
`if("chf1" IS 'true' , 'true','false')`

**Comment by PeterPetrik** [comment]
This does not work on QGIS 3.34.1 (macOS) too 

![Screenshot 2023-12-05 at 15 49 12](https://github.com/MerginMaps/mobile/assets/804608/5fe7b0ae-e75e-43d2-b190-6dcede888190)

**Comment by PeterPetrik** [comment]
To fix this, do not use `'true'` or `'false'` in QGIS projects to represent boolean type, use 'true' and 'false' directly
