### ISSUE TITLE
switching tabs in forms, will make this form blank. 2.5.0

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/mobile#2941]
I was testing unrelated stuff on this project, but I have found out, that while switching among tabs in this point feature form, the form will become blank.
If you manage to fill in some data before it becomes blank, the data will be saved and can be viewed after saving and re-opening this feature. 
I was unable to reproduce with any other form. 

1. open project tc04_geometry_editing (production server, public) 
2. record a point feature in the point layer 
3. while in the form, switch between the 'basic' and 'status' tabs
4. after 2-3 switches, the form will be blank 

https://github.com/MerginMaps/mobile/assets/94351263/8391b37f-95ec-4611-a04e-3eb19fce0a58

**Comment by PeterPetrik** [comment]
is this regression or new bug in RC2.5.0?

**Comment by PatrikMizera** [comment]
new bug in RC2.5.0

**Comment by tomasMizera** [comment]
I can have a look at this one 👀

**Comment by PatrikMizera** [comment]
I am unable to reproduce it now as well, will keep an eye out for this one in the future testing
