### ISSUE TITLE
Input is unable to connect to other devices via Bluetooth, 2.5.0

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/mobile#2943]
Input is unable to connect with other devices via Bluetooth to share GPS info. 

1. open up any project 
2. go to GPS info settings 
3. try to connect to some "visible" device 
4. the connection will fail 

Tested on Xiaomi Redmi Note 10, Android 13, Input 2.5.0

https://github.com/MerginMaps/mobile/assets/94351263/112e520d-9a89-4227-b7e9-a6eca8f427e3

**Comment by tomasMizera** [comment]
I will check this one 👀
