### ISSUE TITLE
possible problem in delete

### ISSUE THREAD

**Issue by PeterPetrik** [MerginMaps/mobile#2947]
this should be `return` @tomasMizera ?

https://github.com/MerginMaps/mobile/blob/4b59718bda38cb2215134ca6f713fc944f2367b8/app/attributes/attributecontroller.cpp#L1063

**Comment by tomasMizera** [comment]
Yeah, either that or wrap lines https://github.com/MerginMaps/mobile/blob/4b59718bda38cb2215134ca6f713fc944f2367b8/app/attributes/attributecontroller.cpp#L1066 and 
https://github.com/MerginMaps/mobile/blob/4b59718bda38cb2215134ca6f713fc944f2367b8/app/attributes/attributecontroller.cpp#L1067

in `else` branch
