### ISSUE TITLE
Accidental double-taps on buttons in relation or image widgets

### ISSUE THREAD

**Issue by erpas** [MerginMaps/mobile#3012]
A user discovered a problem when they accidentally double-tap the `Add` button in a relation widget in the MM mobile app - two features get added and only one of them has reference to the parent feature. This can be a problem when pens or gloves need to be used - accidental double-taps are likely to happen.

The question: is it possible to disable this double-taps in the sense when two taps are found to be too close in time to each-other, one should be ignored?

The same behaviour can be reproduced when adding a photo (either from camera or gallery) - if you double-tap on the cam or gal button, two images are added but only one (the latter) is properly referenced to the feature.

**Comment by jozef-budac** [comment]
@erpas can you please verify this? I was not able to simulate a double-tap problem in any of the scenarios.
