### ISSUE TITLE
Drawer does not disappear when an option is selected

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#3018]
To reproduce the issue:
- Open the app
- Select a project
- Select `... More`
- Select an option (e.g. `Settings`)
- App goes to the setting page but `More options` drawer is still active/open

https://github.com/MerginMaps/mobile/assets/2649047/c8c0a502-9971-4d31-acca-f07583e268d9

**Comment by saberraz** [comment]
Tested in version ` 2024.1.0 (24.1.507711)`

**Comment by tomasMizera** [comment]
Thanks for reporting that though! There will be a dedicated spreadsheet for that
