### ISSUE TITLE
Downloading and then opening projects causes app to freeze

### ISSUE THREAD

**Issue by raherin** [MerginMaps/mobile#3027]
At least one other user with a Samsung A53 has reported similar issues and I have been able to replicate this on my own device of the same model. 

When downloading a project from the server in the Mergin Maps app, the app will frequently freeze or become unresponsive after the user clicks on the project to open it ([see video](https://drive.google.com/file/d/1AA2QT9wtDNJW41cjZav5fEDW9lyyKYuR/view?usp=sharing)). The steps to reproduce this behaviour are as follows:

1. Open the project menu 
2. Go to the search for projects tab
3. Download a new project
4. Click on project when it finishes downloading
5. App crashes
6. Close app
7. Open app
8. Go to project menu
9. Open recently downloaded project from the home tab

This behaviour is random and does not appear to be project specific. When testing this on publicly available projects from the documentation I get the following results:

- sarah/Basic survey: crash
- documentation/forms_one-to-many-relations: no crash
- documentation/form_setup: crash
- documentation/forms_multiple_photos: no crash

However, if I remove one of the projects that did not crash during the first test, sometimes it will crash on the second attempt.

Creating a new project using the mobile app does not cause the app to crash but creating a new project using the default template in QGIS and then downloading and opening it on the mobile device will sometimes cause the app to crash.

**Comment by rvanmaaren** [comment]
The app freezes when opening or downloading a project when the keyboard of the mobile is still open. This seems to be constant.

1. Open the project menu
2. Go to the search for projects tab
3. Download a new project
4. Click on project when it finishes downloading
5. App crashes
6. Close app
7. Open app
8. Go to project menu
9. search for the project 
10. open project (leaving the keyboard open)
11. App crashes
12. close app
13. open app
14. Go to project menu
15. scroll to the project
17. Open project

To not let the app freeze you can either scroll down to the project or close the keyboard from the phone (when using the searchbar) before clicking on download or opening the project.

**Comment by tomasMizera** [comment]
Thanks @raherin and @rvanmaaren for reporting this issue. We will have a look

**Comment by raherin** [comment]
There appears to be an issue related to the virtual keyboard on the Samsung version of Android. Having the keyboard open on the screen, as is often the case when searching for a particular project using the filter, will cause the app to freeze if you try to open the project while the keyboard is still visible. 

One solution that has worked on my Samsung device is to download the standard Google keyboard 'Gboard' and set it to default on your Samsung device:

1. ​Open Google Play
2. Search for Gboard (the default keyboard for Google Android) and install it
3. Open your device settings and go to 'General management' > 'Keyboard list and default'
4. Enable 'Gboard'
5. Click 'Default keyboard' and set it to 'Gboard'

**Comment by volcan01010** [comment]
I have also seen this on my A53.  Thanks for posting the tip about hiding the keyboard.

**Comment by raherin** [comment]
### Update
Since the update to app v2024.1.0 this issue is also affecting Google Pixel phones and the previous workaround of using a non-Samsung keyboard such as GBoard or Simple Keyboard no longer works. See the attached recording from a Google Pixel:

![screen-20240509-100850](https://github.com/MerginMaps/mobile/assets/26321345/595b009b-97a2-4375-844a-7871aece50e5)

**Comment by saberraz** [comment]
Hi @raherin I cannot reproduce this issue on Pixel 8 pro and the latest release.

**Comment by raherin** [comment]
I have tested on both my Pixel 6 and Samsung A53 and the app also freezes if the keyboard is closed. It seems that any time the search filter is used, I cannot open a project. See the below recording from my A53, but my Google Pixel 6 also has this behaviour:

![Screen_Recording_20240509_103138](https://github.com/MerginMaps/mobile/assets/26321345/697920a8-3bc8-4a89-b2c9-a6e8647dae5f)

**Comment by tomasMizera** [comment]
This might be highly related to https://bugreports.qt.io/browse/QTBUG-123876
