### ISSUE TITLE
Incorrect compass direction

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#3074]
Our compass (at least on iOS) often shows incorrect directions. From my observations, it is either 90 or 180 degrees shifted. I double-checked with other apps like Mapy.cz, Google Maps and Apple Maps and they all looked fine. We either receive incorrect data from Qt or somehow break things up while processing.

The bearing seems to be wrong in these situations:
1. After _some_ time of using the app - the bearing suddenly rotates 90/180 degrees
2. When the app is opened from tray - it takes a while for the compass to show the correct bearing

| Example 1 | Example 2 |
|--------|--------|
| <img src='https://github.com/MerginMaps/mobile/assets/22449698/4aa7185b-54d5-488a-bba0-55ff181c2cc5' width=300> |<img src='https://github.com/MerginMaps/mobile/assets/22449698/c98cbd09-8b19-4759-bdb9-8b539f7b051e' width=300> | 

I discovered this while surveying with an iPhone 12.

**Comment by PeterPetrik** [comment]
related #1707
related #2468

**Comment by tomasMizera** [comment]
> related #1707 related #2468

Yeah, let me close the other tickets as duplicates

**Comment by tomasMizera** [comment]
Could not be reproduced these days..

**Comment by jozef-budac** [comment]
It happens from time to time. @tomasMizera, please check it sometimes if it is again reproducible.

**Comment by tomasMizera** [comment]
Ok, I will try out next time :)
