### ISSUE TITLE
predefined picture names do not work after editing geometry

### ISSUE THREAD

**Issue by encleadus** [MerginMaps/mobile#3082]
The expected behavior should be when for photo fields have "Photo attachments configuration" set (in my case ogc_fid.jpg) then the pictures should use that naming. On existing features if I modify the data only, it works as expected, but if I modify the geom as well, the picture naming won't follow the name rule, but they will named with timestamp.jpg

**Comment by tomasMizera** [comment]
Hi there, we are renaming only new photos. Existing photos will not be renamed when updating form.
