### ISSUE TITLE
App freezes on Explorer page

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3206]
When I do some stress tests on the Explorer page I can get into some problems:
1) After hitting the download button, the button is still active and I can hit it again to start downloading again. It should be disabled I think
2) I can get to a problem, I can't download a project at all (first part of the video with the project tc04_photo_rename)
3) I can get into a situation where the application freezes (the last seconds of the video and project tc04_snapping).

https://drive.google.com/file/d/1JyiklxyPlpYDttztFaJrsZzFtLEW4K87/view?usp=sharing

Also on the Home page, I can see multiple projects with same name and download failed:
![image](https://github.com/MerginMaps/mobile/assets/83582181/c043a551-1d9f-42fa-8779-d24b0c24e931)

**Comment by tomasMizera** [comment]
That is indeed very stressful, just watching you tap download button 20 times raises my heart beat 😀
