### ISSUE TITLE
Closing user account UI/UX issues

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3207]
When I try to close the user account with a active workspace, there are two UI/UX problems
1) The Yes button should be enabled only when the correct user name is entered
2) when I enter the correct name and hit yes, the notification appears on the top of the page, but it is behind the modal window. It should be before

![image](https://github.com/MerginMaps/mobile/assets/83582181/872f6328-134d-4606-9996-933c55449250)
![image](https://github.com/MerginMaps/mobile/assets/83582181/67b2d17b-a051-45f4-a857-2d257d82c7c9)

2nd problem makes notifications invisible in landscape mode

https://github.com/MerginMaps/mobile/assets/83582181/06562e08-8989-4803-853d-6194f44203a4

**Comment by PeterPetrik** [comment]
2/ is already fixed in https://github.com/MerginMaps/mobile/pull/3204

**Comment by PeterPetrik** [comment]
1/ @tomasMizera do we have defined in design system how disabled button in grape/red version should look like ?

**Comment by PatrikMizera** [comment]
present also on Android (Xiaomi Redmi Note 10S) 2024.1.0-rc2
