### ISSUE TITLE
Offline problems

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3210]
There are multiple problems when apps don't have a connection to the internet (others than https://github.com/MerginMaps/mobile/issues/3194)
1) The button for Retry is badly formatted
![image](https://github.com/MerginMaps/mobile/assets/83582181/0d5aaa75-938c-48bd-9f0b-0a06c07cc8b7)
Even in landscape mode:
![image](https://github.com/MerginMaps/mobile/assets/83582181/0f537143-15a7-4e14-95ac-fac4c229ce99)

2) On the Project page, the loading icon is still loading, even when there is no connection
![image](https://github.com/MerginMaps/mobile/assets/83582181/fb50ee6c-52ed-4a7e-8f63-0bf2658821bf)

3) When I have two local projects, after the restart of the app, only the first project is visible. Then I open it and go to the home page again, there is the second one visible, and the first is missing. 

https://github.com/MerginMaps/mobile/assets/83582181/57b7f580-e992-4854-b1ac-80a4dc16aa37

**Comment by jozef-budac** [comment]
Related to https://github.com/MerginMaps/mobile/issues/2597

**Comment by PatrikMizera** [comment]
present also on Android (Xiaomi Redmi Note 10S)

**Comment by wonder-sk** [comment]
Hmm actually I can't replicate (2) properly...

On Android, when there's no internet (disconnected wifi / mobile data), I am getting a network error as expected and the list of projects in Home tab shows up, and in Projects tab I get the "Unable to get the list of projects" full-screen error.

On Linux, it is a bit worse, after disconnecting from wifi, network requests may end up being stuck forever, but then on the next try when I reopen Projects page, things start to behave well and all network requests fail quickly, with correct GUI updates.

I have not tried on ios...

**Comment by tomasMizera** [comment]
I could not reproduce it anymore on iOS too :)

**Comment by jozef-budac** [comment]
For the 2nd problem, it is the edge case, but you can simulate it this way
1) in the mobile app login to the account and display the project page
2) disable WiFI and check that both the Project and Explore page shows the correct error page
3) go to the profile Page and get back to the project page -> you can see the loading icon.


https://github.com/MerginMaps/mobile/assets/83582181/4b341156-24fa-40bc-b354-3de339cbfe29
