### ISSUE TITLE
MM Tips in landscape mode are not visible

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3212]
In landscape mode, the MM tips are not visible. For example on creating the workspace page, you can see "Tips from Mergin Maps" below on the screen, but in landscape mode, they are missing

https://github.com/MerginMaps/mobile/assets/83582181/e267162b-5e2a-4141-ba62-4c5caa8714ed

**Comment by tomasMizera** [comment]
This is intentional :) otherwise, you would not see the button to continue immediately and would need to scroll. It is visible though on tablets in landscape - they have enough vertical space
