### ISSUE TITLE
Upload a new project with sync button when user is logged out 

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3216]
When a user is logged out and tries to upload a project with the Sync button in the project, a new dialog with the "Upload project?" notification appears. After hitting Yes, nothing happens. The expected behavior is the app to show Log-in page. 

https://github.com/MerginMaps/mobile/assets/83582181/51255b5b-d389-4f71-aad0-85ea62d7216d

**Comment by tomasMizera** [comment]
Solution: 
 - when not logged in -> open drawer "log in" then
 - when project is not uploaded to cloud yet -> open drawer "upload to MM"
