### ISSUE TITLE
Canceling of project upload makes a little mess

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3217]
When I upload a new project and then cancel the upload it

1. show notification about "Failed to communicate with the server" which is not true
2. Both upload and synchronize buttons are missing for the project even when it was not uploaded fully (till I refresh the page)
3. After refreshing, there is a "Not uploaded" notification for the project but when I hit it, it says, the project with the name exists - which is true, because the project was created but the files were not synchronized.

I am not sure how big a problem it is, but I would address at least the first problem

https://github.com/MerginMaps/mobile/assets/83582181/6cf81d73-012e-4f35-a69c-de8991fb3748

**Comment by PeterPetrik** [comment]
related to https://github.com/MerginMaps/mobile/issues/1914
