### ISSUE TITLE
Can't scroll in map themes when in landscape mode

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3220]
When there are multiple map themes, you can't scroll when the phone is in landscape mode. You can get to the bottom of the list. 

Scenario
1) open the project tc03_map_canvas 
2) go to map themes and turn mobile to use landscape mode

https://github.com/MerginMaps/mobile/assets/83582181/8c1c011f-b5e6-4922-9d16-65662988139e

**Comment by tomasMizera** [comment]
Solution: change 
https://github.com/MerginMaps/mobile/blob/45e93575a8b37390261d657b05981f308f54ce2b/app/qml/main.qml#L496

from `height` to `maxHeight`
