### ISSUE TITLE
External GPS problems

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3222]
There are a few problems with external GPS receivers

1) the styling of "Manage GPS receivers" is very bad. All the text is on the left side. In landscape mode, it is even worse.
2) there is the possibility to remove the "Internal" receiver, which doesn't remove it. This option should not be present for internal GPS receivers
3) On iPhone, I believe, we still don't have the option to connect to an external Bluetooth device. Previously, we displayed a message about it. Now there is a button to add a new device there. 

https://github.com/MerginMaps/mobile/assets/83582181/1bc2278e-9535-47f2-9736-b6a74522a681

**Comment by PeterPetrik** [comment]
3/ the message width is fixed here https://github.com/MerginMaps/mobile/commit/1015327909cc57d4b8f39f07b53b29fac5ebd020, we still need to remove button on iOS
