### ISSUE TITLE
Streaming mode problems

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3224]
There are two problems for the streaming mode

1) it is available for point and multipoint features, which is an error
2) There is a scenario, in which the streaming option becomes unavailable till the restart of the app. The scenario is
- open the project tc04_recording
- record the multipoint feature .. add a few points and hit "record"
- on the form hit Edit geometry - remove one point and hit save
- from now on, instead of the streaming mode icon, there is 3 dots icon, which shows an empty menu. The only way how to see streaming mode again is to restart the app.

https://github.com/MerginMaps/mobile/assets/83582181/105d2a24-491d-4d86-a04c-b7fd2c79acdd

**Comment by PeterPetrik** [comment]
why it shouldn't be available for multipoint?

**Comment by jozef-budac** [comment]
That is my mistake. Yes, probably the only point is problematic. I checked, that on current production, the streaming mode is available also for points. So I changed the tag to bug.

**Comment by jozef-budac** [comment]
Related to https://github.com/MerginMaps/mobile/issues/2565
