### ISSUE TITLE
Cannot record a point with photo

### ISSUE THREAD

**Issue by harminius** [MerginMaps/mobile#3225]
I want to add a point with picture. When I take the photo the camera is still open and when I take a photo for the second time, I'm back in the app but the point is not recorded.

Phone info: Google Pixel 4, Andoid 13

Log: https://drive.google.com/file/d/1wWvMJPJKJ9WCPg_ztfqR2Ez_FnFKU-_F/view

https://github.com/MerginMaps/mobile/assets/28006188/a6624747-724a-4d64-9d4b-42fea62b625d

**Comment by tomasMizera** [comment]
I can reproduce similar issues with the camera too 👌🏻

**Comment by tomasMizera** [comment]
I could not reproduce this on multiple devices :/
