### ISSUE TITLE
Fonts are too small in vector tile layer

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#3227]
I am creating a project from project wizard which has our vector tile layer. But the fonts are very small on my Google Pixel 8 Pro.
<img src="https://github.com/MerginMaps/mobile/assets/2649047/372b517a-a39e-4dc2-9836-bd4f41f6cdba" width=400>

**Comment by tomasMizera** [comment]
Hi @saberraz, can you please add a screenshot from the previous version?

**Comment by saberraz** [comment]
Here is the same layer in the current release version of the app:
![Uploading screenshot_20240405-153731.png…]()

**Comment by wonder-sk** [comment]
(we are unable to replicate the problem with font sizes)
