### ISSUE TITLE
Checkbox field are always active when once selected

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3240]
When the checkbox field is made active (the border is dark green) it stays active even when another field is activated.
To simulate this click multiple times on the switch so it gets active. 
Maybe this is problem only on iPhone. 

![image](https://github.com/MerginMaps/mobile/assets/83582181/b79fabd9-f621-4106-8812-3893e713fb3f)

https://github.com/MerginMaps/mobile/assets/83582181/2e7c148b-008f-45cb-a808-eedf84355557

**Comment by tomasMizera** [comment]
Aha, so this is an issue with the focus
