### ISSUE TITLE
Exif data are not read from gallery picture

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3243]
When I take picture with a camera, the EXIF data are read properly. When I use picture from the gallery, the EXIF data are missing. I the video you can see, that I opened the same picture in a different app and the EXIF data were present.

For testing you can use project tc05_form_derived and form's tab `Exif`

https://github.com/MerginMaps/mobile/assets/83582181/f8cedb08-23e4-4e3d-a878-58ab776519d0

**Comment by tomasMizera** [comment]
Dup of https://github.com/MerginMaps/mobile/issues/1836
