### ISSUE TITLE
Map themes dialog problems

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3244]
1) The map themes list is not scrollable, so when there are more than 5 themes, you can't go the to 6th. 
In landscape mode, it is scrollable, but you can't scroll to the last one.

you can test it in tc06_data_providers project

![image](https://github.com/MerginMaps/mobile/assets/83582181/5eff23e4-9d22-4d75-965c-0bddcf8e6397)

2) when no Map theme exists, there is a link to "how to setup themes", but the link does nothing

3) in landscape mode, the "No map theme" dialog is partly hidden below the display and can't be scrolled down

![image](https://github.com/MerginMaps/mobile/assets/83582181/d349c1cc-cf17-4a8e-b988-ff968d9c16fb)

**Comment by tomasMizera** [comment]
Dup/relates to #3220
