### ISSUE TITLE
Project tc08_selective_sync has pending changes right after download

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3245]
When you download input-testing/tc08_selective_sync project, there will be a "Pending changes to synchronize" warning on the project, even when there are none.
The same happens when you clone the project to your workspace and download it to the app.

**Comment by tomasMizera** [comment]
Isn't it the same as https://github.com/MerginMaps/mobile/issues/3129? @jozef-budac Can you please check how it behaves on 2.5.0? I believe this is already in the production

**Comment by jozef-budac** [comment]
Yes, it behaves the same in 2.5.0, so this is a duplicate

**Comment by tomasMizera** [comment]
Dup of #3129
