### ISSUE TITLE
Frequent crash and UI freeze when dealing with a large form. See lutraconsulting/12_form_group project.

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#3253]
Reported by @saberraz [ISS-89]

Frequent crash and UI freeze when dealing with a large form. See lutraconsulting/12_form_group project.

**Comment by uclaros** [comment]
Cannot replicate this on Linux build, only sometimes the openstreetmaps tile server is a bit slow to reply. Do you have some specific actions that would trigger the freeze/crash @saberraz ?

Also, not sure if this is a bug, but it looks like the forms for this project have a fixed width, not fitting in a portrait orientation:
![image](https://github.com/MerginMaps/mobile/assets/11358178/8fbe6f9f-725f-480f-a404-45f3eb6de1f1)

Enlarging the window makes the contents appear but then they do not stretch to fit the width:
![image](https://github.com/MerginMaps/mobile/assets/11358178/4ffd8275-3b51-4720-aa4a-bb4b68e0b7ce)

**Comment by tomasMizera** [comment]
> Cannot replicate this on Linux build, only sometimes the openstreetmaps tile server is a bit slow to reply. Do you have some specific actions that would trigger the freeze/crash [@saberraz](https://github.com/saberraz) ?
> 
> Also, not sure if this is a bug, but it looks like the forms for this project have a fixed width, not fitting in a portrait orientation: ![image](https://private-user-images.githubusercontent.com/11358178/320880632-8fbe6f9f-725f-480f-a404-45f3eb6de1f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Mzc3MTksIm5iZiI6MTcxMjczNzQxOSwicGF0aCI6Ii8xMTM1ODE3OC8zMjA4ODA2MzItOGZiZTZmOWYtNzI1Zi00ODBmLWE0MDQtNDVmM2ViNmRlMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA4MjMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmM2FjNTMyZjZhNTBiZTA1ZmVjZWQ4NmQzMzA5OGVhNWM4M2ZjZmJjMDM2YTYxYTQ4ODJjMzAxNGE2ZmJjY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IuikGrQCKQU3fiQ5xV-jKXo3U3-wxYJ0bHQYI3PtaKY)
> 
> Enlarging the window makes the contents appear but then they do not stretch to fit the width: ![image](https://private-user-images.githubusercontent.com/11358178/320882190-cd9d58d3-3d76-4058-8d86-6829a85b76ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Mzc3MTksIm5iZiI6MTcxMjczNzQxOSwicGF0aCI6Ii8xMTM1ODE3OC8zMjA4ODIxOTAtY2Q5ZDU4ZDMtM2Q3Ni00MDU4LThkODYtNjgyOWE4NWI3NmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDA4MjMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMGI0OGM4MDI4NThkNTBhYmM2OWU1MjAyNDhhZDg5YWQyNTVjOTdiY2Q0ZDc3MGFkNDg5M2Y0OTc0ZjQzNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oRGRJ_Fx0Ja52F8bkL5sea-GiB-ny4Cb5nY6bWeHVOw)

Hi @uclaros can you please file a bug report for this issue?

**Comment by saberraz** [comment]
I tested this with an earlier RC and it seems to be working now after value maps issues have been addressed.
