### ISSUE TITLE
the sync button does not work when you are logged out, but the project is already uploaded to the workspace,

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/mobile#3267]
In this scenario, the projects have been uploaded to the server before. You are logged out and try to sync changes, but the sync button does nothing, only after you go to the 'home' page and try to sync the project there, will you see the error message that you are logged out. 

present on Android (Xiaomi Redmi Note 10S)

https://github.com/MerginMaps/mobile/assets/94351263/ae031d41-7277-4337-9c00-1b98c765f781

**Comment by tomasMizera** [comment]
Dup of #3216
