### ISSUE TITLE
unable to move across the screen while in stake-out mode

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/mobile#3272]
When you enter the stake-out mode and you want to move across the screen, you will be kicked out of the stake-out mode. 

https://github.com/MerginMaps/mobile/assets/94351263/5e996dc4-66bb-427e-ab49-3a226cb50ff3

**Comment by uclaros** [comment]
Should be fixed with #3265

**Comment by tomasMizera** [comment]
As @uclaros said, already fixed now on master :)
