### ISSUE TITLE
the time is not updated when you click on it 

### ISSUE THREAD

**Issue by PatrikMizera** [MerginMaps/mobile#3274]
When you go to edit a feature and it has a time field, the field is not updated to the current time. 

https://github.com/MerginMaps/mobile/assets/94351263/62d2eb34-2398-40d6-8795-22a11431fdd0

**Comment by tomasMizera** [comment]
Can you please give us more information? What is wrong here? What is the configuration of the field? What is expected to happen?

**Comment by tomasMizera** [comment]
@PatrikMizera

**Comment by PatrikMizera** [comment]
Sorry my mistake. After further investigation, I think the bug is in the calendar button (located at the end of the text field), when you press the calendar button in the old version, the date is automatically updated to the current one. However, in the new version, when you press the calendar button, the date is not updated automatically, it will open the date selection.  

https://github.com/MerginMaps/mobile/assets/94351263/7fb1ccbc-0956-4de9-b6d0-ff25b2518c04


https://github.com/MerginMaps/mobile/assets/94351263/d34215f8-26af-4478-a091-d28d7d261539

**Comment by tomasMizera** [comment]
Ah, good then 😌 This is as expected :) Can you update the test procedure, please?
