### ISSUE TITLE
"Create workspace" button slightly overlaps with navigation bars (Android)

### ISSUE THREAD

**Issue by alex-cit** [MerginMaps/mobile#3277]
There is a difference in the position/appearance of  **Create project** and **Create workspace** buttons. While the **Create project** button seems okay, the **Create workspace** button slightly overlaps with the bottom navigation bars in Android. 

![Screenshot_20240407_114529](https://github.com/MerginMaps/mobile/assets/94905350/0b1da38a-0fe5-41e2-9a25-891777e244e7)
![Screenshot_20240407_114522](https://github.com/MerginMaps/mobile/assets/94905350/f64a389b-2a2a-411c-9310-6688972bd04f)

**Comment by PeterPetrik** [comment]
@alex-cit which app build?  Does it show the error also when you clearly close and start app and go to the page? Or only when you turn to landscape and back to portrait?

**Comment by alex-cit** [comment]
It showed everytime I went to the page, I did not turn to landscape mode (I used portrait mode). I am using Samsung Galaxy A52.
Not sure about the build, it shows as version v2024.1.0, I installed it sometimes last week through Google Play, Tomas added me to the testing group.
