### ISSUE TITLE
Hyperlink does not work in the Preview Panel and Form

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#3289]
1. Open `documentation\forms-navigation-link `project
2. Tap on the red dot near Sheffield
3. From the preview panel, tap on Open Google Map (bug 1: it should open the hyperlink instead of opening the form
4. The form opens
5. in the google map field, tap on Open Google Map (bug 2: nothing happens)

bug 3: The hyperlink font and style both in the form and in the preview panel is very invisible and washed out. It should be a bit more blue!

**Comment by PeterPetrik** [comment]
This is in RC or release 2.5.0?

**Comment by saberraz** [comment]
This is RC only. It works fine in the current official release.

**Comment by PeterPetrik** [comment]
> This is RC only. It works fine in the current official release.

Ok cool, in that case "bug in not released version" is correct label

**Comment by PeterPetrik** [comment]
duplicate/related to https://github.com/MerginMaps/mobile/issues/3275
