### ISSUE TITLE
App crashes when screen is rotated during QR code scanning

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#3296]
To reproduce:
 - open QR code scanner
 - rotate screen
   - 💥 

Reproduced on Android, iOS works fine.

I managed to get the same stacktrace (crash) when doing the following:

 - Open form that has an image field and a QR code field
 - Add image
 - Immediately after the image is captured open the QR code scanner
  -  💥 

A Quick Google search showed this Qt bug: https://bugreports.qt.io/browse/QTBUG-119445 <-- the same stacktrace

I tried to apply the fix mentioned in this comment https://bugreports.qt.io/browse/QTBUG-119445?focusedId=760746&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-760746 but that only led to other issues with the camera.

One possible solution could be to lock the screen orientation when opening the QR code scanner, see https://stackoverflow.com/questions/34310349/temporarily-programmatically-disable-screen-rotation-in-qt

I did not test the current 2.5.0, so not sure if it is a regression or not.

**Comment by wonder-sk** [comment]
I can get a crash in this scenario:
- open QR scanner in form
- close the QR scanner
- switch to android home page (or another app)
- switch back to MM
- open QR scanner in form again - crash 💥 

Rotating screen never crashed it for me, but if I rotate the screen from portrait to landscape, the camera preview ends up not not getting rotated correctly (and rotating back to portrait messes up the camera preview orientation there as well).
