### ISSUE TITLE
Loading icon should in in the middle

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3356]
When data are loading (for example on the explore page), the loading icon is on the top left corner. I believe it should be somewhere in the middle

A freshly installed application is probably needed for this to appear.

https://github.com/MerginMaps/mobile/assets/83582181/343bf83b-6afa-4b38-ad98-bcf9f9d8f5aa

**Comment by PeterPetrik** [comment]
@jozef-budac is this still the case? I cannot reproduce it on master on macOS build. 

https://github.com/MerginMaps/mobile/assets/804608/a4156ce6-dbd8-47d9-86e0-fa659042dccf

**Comment by jozef-budac** [comment]
Yes, it is there. Firstly, when you load the page, it is in the middle. But when you adjust the search, it will be in the top left corner



https://github.com/MerginMaps/mobile/assets/83582181/5697bacb-3ed3-44ab-a7de-32fadb628b80

**Comment by jozef-budac** [comment]
Verified on 2024.3.0 RC
