### ISSUE TITLE
App freezes when switching betwee Home and Projects page while searching projects

### ISSUE THREAD

**Issue by uclaros** [MerginMaps/mobile#3389]
- Go to Home page
- Type in a string to the search bar
- Switch to Projects page

also happens from Projects to Home

**Comment by tomasMizera** [comment]
This might be fixed by #3462, can you please test @jozef-budac ?

**Comment by uclaros** [comment]
Note that I could only reproduce this on my phone

**Comment by tomasMizera** [comment]
Could you check @uclaros on your phone then, please? 🙏🏻

**Comment by uclaros** [comment]
> Could you check @uclaros on your phone then, please? 🙏🏻

@tomasMizera It does not fix it, you would need to unset the focus also when changing through the states/pages in MMProjectController.

**Comment by tomasMizera** [comment]
Makes sense @uclaros 👍🏻  thanks

**Comment by jozef-budac** [comment]
on current 2024.2.0 it looks like this is not a problem anymore

**Comment by uclaros** [comment]
@jozef-budac this is a semi-local issue. I can only replicate on my phone, Mi A3, Android 11

**Comment by jozef-budac** [comment]
so can you try that it is fixed on your phone @uclaros?

**Comment by uclaros** [comment]
I've tested with the artifact from #3462 and it's still there. Are there any changes that suggest it may be fixed in another version?
