### ISSUE TITLE
Empty entries created when creating and deleting a local project that could not be uploaded due to project limits

### ISSUE THREAD

**Issue by alex-cit** [MerginMaps/mobile#3403]
RC4 for 2024.1.0

There are two existing projects in the workspace (the limit for projects in this workspace).
What I did:
1. Created a new project
2. Tried to upload it to the server - there is the message about the maximum number of projects, so cannot upload
3. Removed the local project from the device
4. Switched to the **Projects** tab and back the **Home** tab
In the Home tab, there is now an empty project entry in **Downloaded projects** - when I click on the three dots, the message about the maximum number of projects appears again. When clicking the three dots again,nothing happens.

5. Switched between the **Projects** and **Home** tabs again, there are now 2 empty entries.

The empty entries dissapear when closing the app and opening it back again.

https://github.com/MerginMaps/mobile/assets/94905350/e62a708a-03b7-4548-9e6c-0cc1c54a13f7

**Comment by jozef-budac** [comment]
I can't reproduce this on 2024.2.0 RC. @alex-cit , can you please verify it also?
