### ISSUE TITLE
UK/US english in the app - synchronise vs. synchronize

### ISSUE THREAD

**Issue by alex-cit** [MerginMaps/mobile#3404]
RC4 for 2024.1.0

I've noticed that there are both UK and US spelling of the word synchronise/synchronize used in the app.

![image](https://github.com/MerginMaps/mobile/assets/94905350/644df0d8-8a5e-4d1c-89a3-177c529648df)

In the docs, we use UK english and it would be best to have it the same in the app and other components. So I would vote for **synchronise** :)

**Comment by jozef-budac** [comment]
Verified on 2024.1.1
