### ISSUE TITLE
Not possible to edit a photo field in a form if the photo is missing

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#3405]
To reproduce, 

- Create a project in QGIS
- Assign attachment widget to a field
- Attach a photo 
- Download on the mobile app
- Now back on computer, delete the photo file and sync the project
- Sync the project on the app
- Open the feature in the app
- No indication of the missing photo AND not possible to use Delete button to re-assign/re-take a new photo

See: https://app.merginmaps.com/projects/saber/uq-test (feature ID 4):
![image](https://github.com/MerginMaps/mobile/assets/2649047/4310eaa2-a434-4272-bdc4-a43d0af2dde7)

**Comment by tomasMizera** [comment]
Hi @saberraz can you still reproduce this ticket in 2024.1.1?

**Comment by jozef-budac** [comment]
Verified on 2024.2.0 RC. In the Saber's project in the feature with ID 4, I was able to take a new picture.
