### ISSUE TITLE
Glitchy scrolling in drawers

### ISSUE THREAD

**Issue by VitorVieiraZ** [MerginMaps/mobile#3412]
Currently, in MMDrawer with ListView, the drawer closes when dragged from the top. We need to modify this behavior to only allow closing the drawer using the close button, rather than by dragging.

**Comment by jozef-budac** [comment]
Should this work also for the preview panel?
https://github.com/MerginMaps/mobile/assets/83582181/bf8e6f6a-a0d7-4c4f-a09f-882edb387f97

**Comment by tomasMizera** [comment]
> Should this work also for the preview panel?

@jozef-budac that looks all right :) Only drawers that would scroll are disabled for now
