### ISSUE TITLE
Photo renaming does not work when multiple photo fields have custom expressions

### ISSUE THREAD

**Issue by raherin** [MerginMaps/mobile#3415]
I have been able to recreate an issue reported by at least one other user where multiple photo naming expressions are used in 'Project>Properties', only the first listed expression will be applied in the app. 

I have a project with two point survey layers. The first survey layer has two photo attachment fields and the second layer has one photo attachment field. In my project directory, I have a 'photos/' folder to store photo attachments. In the project properties, I have a photo naming expression set for each attachment field, the same expression is used for each field:

`'photos/'||@mergin_username||'-'||@layer_name||to_string("count")||'_'||format_date("date",'yyyy-MM-dd_Thh.mm.ss')`

<img width="885" alt="image" src="https://github.com/MerginMaps/mobile/assets/26321345/0b049126-598c-43e7-947e-1786cb8fb3ce">

In the app, I add a feature to `Survey` layer and add two photo attachments
![Screenshot_20240509_163349](https://github.com/MerginMaps/mobile/assets/26321345/8ee68217-af2e-498a-a375-78c8a7711961)

I then add a feature to `survey2` layer and add one photo attachment
![Screenshot_20240509_163428](https://github.com/MerginMaps/mobile/assets/26321345/050aaefb-3a3d-4b39-90e8-ad007a769928)

I then synchronise the changes in the mobile app and go back to sync in QGIS, however I can see that the photo naming expression was only applied to one of the three photos I just recorded in the app
<img width="554" alt="image" src="https://github.com/MerginMaps/mobile/assets/26321345/e407018f-2f65-4f9e-9dab-8603151a3204">

If I go to the project directory, I can see that two of the photos did not get saved to the /photos folder and the photo in the `Survey.photo` field is in the /photos folder with the correctly applied custom name

<img width="701" alt="image" src="https://github.com/MerginMaps/mobile/assets/26321345/92ffa396-0b95-40fa-b0b1-2a0fe1772332">

photos/
<img width="658" alt="image" src="https://github.com/MerginMaps/mobile/assets/26321345/476dea4b-b617-4d7a-8bde-1fa5abe3eaff">

**Comment by tomasMizera** [comment]
@raherin

**Comment by tomasMizera** [comment]
@raherin can you share the project with us please?

**Comment by raherin** [comment]
@tomasMizera you can find the project [here](https://app.merginmaps.com/projects/support/photo_names-test/collaborators), I have given you 'Owner' rights to add more users if needed.

**Comment by jozef-budac** [comment]
@tomasMizera @raherin , can you please share this project with me? I want to verify the fix. Thanks

**Comment by VitorVieiraZ** [comment]
> [@tomasMizera](https://github.com/tomasMizera) [@raherin](https://github.com/raherin) , can you please share this project with me? I want to verify the fix. Thanks

Hi @jozef-budac, I just shared this project with you.
