### ISSUE TITLE
App will freeze in some cases when an integer field has 'not null' constraint and no default value

### ISSUE THREAD

**Issue by raherin** [MerginMaps/mobile#3417]
I have identified a condition where the app will freeze when there is a field with an integer data type that has a not null constraint and no default value is set. There are also two other specific conditions to cause the freeze. The form must be long enough that the user has to scroll to see all of the fields and it will not freeze until a second feature is created after editing or creating a feature and saving it. I have created an example project [support/test-not-null-int](https://app.merginmaps.com/projects/support/test-not-null-int/) to test the issue. To recreate the problem:

1. create a survey layer that:

- has at least enough fields that the user must scroll in the app to see them all (at least 7)
- has at least one field that has an integer data type

2. give the integer field a 'not null' constraint but do not set a default value
3. synchronise the project with the QGIS plugin
4. download the project and open it in the app
5. record a new feature on the survey layer, make sure all of the constraints are met and save the feature
6. press the '+' button and 'record' to add a second feature
7. when the form view opens, scroll up and down the form
8. the app will freeze

I have tested this on a Samsung A53 with Android 14 installed. At least one other user has reported a similar issue on their Android 14 device.

**Comment by raherin** [comment]
In addition to the above conditions, I was able to reproduce app freezes with other data type and widget combinations with 'not null' constraints. I've created another project to reproduce this [support/form-freeze-test](https://app.merginmaps.com/projects/support/form-freeze-test/tree)

Using the example project, the following conditions caused freezing in the app:

| Data type | Widget type | Contraint | Default | When did app freeze? |
|------------|---------------|------------|---------|---------------------------|
| text | Value map | not null | no default | (1st feature edited after last sync) |
| int32 | range | not null | no default | (1st feature edited after last sync) |
| int32 | range | `"number" >= 1` | no default | (1st feature edited after last sync) |
| text | attachment(photo) | not null | no default | (2nd feature edited after last sync) |

**Comment by raherin** [comment]
@tomasMizera we also got app crashes on iPad. Though it needed to be in landscape mode so that you had to scroll to see the whole form. If it is in portrait mode and you do not need to scroll, the app does not crash. Also the app did not crash if values were entered to not null fields before scrolling. It only crashed when not null fields are empty and you scroll on the form.

**Comment by tomasMizera** [comment]
Thanks @raherin for testing this out!

**Comment by jozef-budac** [comment]
I can't reproduce the crash on the current 2024.2.0 RC. @raherin , can you please verify it also?
