### ISSUE TITLE
Merginmaps crashing not null

### ISSUE THREAD

**Issue by SphagnumPI** [MerginMaps/mobile#3428]
Merginmaps app crashes if the not null constraint is ticked and whether enforced or not. Removing these contraints results in no crashing. This is both on Samsung and Apple

**Comment by raherin** [comment]
@SphagnumPI Is the constraint on a text field or other data type?

**Comment by raherin** [comment]
@SphagnumPI please submit a ticket for our support team to look at, you can do so by going to this link: https://support.merginmaps.com/support/tickets/new
