### ISSUE TITLE
Enable text predictions on Android

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#3434]
Disabled in https://github.com/MerginMaps/mobile/pull/3318, let's enable it back

**Comment by tomasMizera** [comment]
Our thinking is that it can help with #3428 and #3417.

**Comment by PeterPetrik** [comment]
is this something with `QT_ANDROID_ENABLE_WORKAROUND_TO_DISABLE_PREDICTIVE_TEXT` env variable?

**Comment by PeterPetrik** [comment]
> Our thinking is that it can help with #3428 and #3417.


> Our thinking is that it can help with #3428 and #3417.

problem is that the freezes are also on macOS, etc., not just android

**Comment by jozef-budac** [comment]
I can insert text with a speech-to-text functionality. Also, I can use prediction on Samsung keyboard
