### ISSUE TITLE
In maintenance mode, the appr after restart doesn't show a notification about it.

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3451]
In maintenance mode, the appr after restart doesn't show a notification about it.
When the server gets into maintenance mode, firstly it shows a red notification about maintenance mode. However, after the app restarts, the notification is not displayed. Only on the Signup page it is said, that the server is unavailable. 

Also there is a small problem, when synchronization fails, there is the message learn more, which can't be clicked

![image](https://github.com/MerginMaps/mobile/assets/83582181/19fed153-5ec1-41cf-8b46-6f015d44af65)

This but is in not released, because the maintenance mode was not released yet :)

**Comment by tomasMizera** [comment]
Expected resolution:
 - Handle click on the notification and open the sync failed dialogue, there is a TODO for that, see https://github.com/MerginMaps/mobile/blob/92e08bbd1497c3837df178bbd232e49110f511f8/app/qml/main.qml#L840

**Comment by jozef-budac** [comment]
The problem with clicking on "Learn more" was fixed. But the problem, that the notification doesn't show up after app restart is not fixed @tomasMizera?

**Comment by tomasMizera** [comment]
> The problem with clicking on "Learn more" was fixed. But the problem, that the notification doesn't show up after app restart is not fixed @tomasMizera?

@jozef-budac Let's create a dedicated bug report for that please :)

**Comment by jozef-budac** [comment]
OK, I will do that, but I will just copy what is here :)
