### ISSUE TITLE
"Unique" and "Enforce Unique constraint"  does not work

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#3457]
I have a sampling layer the auto creates the field station_id off of a prefix, geologist and station_number . And then I have set this field to be "Unique" and "Enforce Unique constraint" in QGIS. In the screenshot below (I had already taken a sample named "SM2024_Elliot_001") it appropriately will not let me save this point (note the red check mark in top right corner!), however it does not give me any warning that the station_id is the culprit! When I add station number to 2 the station_id changes appropriately, and I can save the point. But it would be helpful to get a warning pop up about Unique values just like there are warnings for Null values!
![image](https://github.com/MerginMaps/mobile/assets/2649047/ed870e7e-1e54-4408-884c-6be8e7442d44)

**Comment by tomasMizera** [comment]
I can't reproduce it. This is my QGIS setup:
<img width="581" alt="image" src="https://github.com/MerginMaps/mobile/assets/22449698/19a23e36-4e15-4e23-8e26-a977428488ec">

and in the app I can clearly see the unique constrain validation:

<img width="346" alt="image" src="https://github.com/MerginMaps/mobile/assets/22449698/f00d8c65-5b75-446e-8a5a-bcb1804179db">

@saberraz let me please know if I am doing something wrong

**Comment by VitorVieiraZ** [comment]
I couldn't reproduce the bug either; the functionality is working as expected.

**Comment by saberraz** [comment]
I have a project to test it with

**Comment by tomasMizera** [comment]
> @VitorVieiraZ please coordinate with @saberraz to test the project

It was me :D

**Comment by wonder-sk** [comment]
@VitorVieiraZ I have a test project + steps to reproduce

**Comment by jozef-budac** [comment]
@saberraz @VitorVieiraZ @wonder-sk  .. can you please verify this? Or can share a test project and the steps with me? Thanks

**Comment by VitorVieiraZ** [comment]
> @saberraz @VitorVieiraZ @wonder-sk .. can you please verify this? Or can share a test project and the steps with me? Thanks

Hi Jozef! I have just shared it with you [here](https://app.dev.merginmaps.com/projects/MobileTests/iss3475_UniqueConstraintBug/tree).
