### ISSUE TITLE
Form section headers do not wrap

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#3463]
Form section headers do not wrap, nor elide (...). Let's make sure they wrap to 3 lines and then elide (add 3 dots to the end).

<img width="365" alt="image" src="https://github.com/MerginMaps/mobile/assets/22449698/87e628c3-e497-4d52-af30-bf65949fa3b0">

**Comment by tomasMizera** [comment]
`elide`, `wrapMode` and `maximumLineCount`

**Comment by jozef-budac** [comment]
Verified on 2024.3.0 RC 

https://files.slack.com/files-pri/TBXE5PUU9-F0795HJ9T4J/screenshot_20240621_112735.jpg
