### ISSUE TITLE
Bug with multiple select value map and not null constraints 

### ISSUE THREAD

**Issue by MTrim** [MerginMaps/mobile#3476]
I have set up a layer with an attribute field. As type I am using a valuemap, multiple selections and "enforce not null constraint"
In the mobile App there is a bug. Just selecting a value doesn't work. I have to select a value, deselect it and select it again (see video)
https://www.loom.com/share/1c289eabd95c420780538c587855faed?sid=59996c69-9d72-46f4-914a-14c2aff41b3c

**Comment by tomasMizera** [comment]
Hi @MTrim, thanks for reporting this. It sounds like a duplicate of this ticket https://github.com/MerginMaps/mobile/issues/3418. The issue will be fixed in the upcoming version. Feel free to reopen is it is not the same bug

**Comment by MTrim** [comment]
Hi @tomasMizera, it' exactly the same. Sorry for the duplicate, didn't saw the other issue.
Thank you ;-)
