### ISSUE TITLE
Bump target SDK version to Android 14

### ISSUE THREAD

**Issue by wonder-sk** [MerginMaps/mobile#3481]
- we're targeting Android 13 (API level 33) right now (also default for Qt 6.6.3)
- Google Play will likely require Android 14 from September 2024
- Qt 6.7 has Android 14 as the default target (but we probably don't need to upgrade Qt)
- behavior changes when we switch: https://developer.android.com/about/versions/14/behavior-changes-14

**Comment by tomasMizera** [comment]
We need to double-check these two things:
- https://developer.android.com/about/versions/14/behavior-changes-14#enforce-bluetooth_connect
- https://developer.android.com/about/versions/14/behavior-changes-14#partial-photo-library-access
