### ISSUE TITLE
App freezes during recording child feature in relations

### ISSUE THREAD

**Issue by jozef-budac** [MerginMaps/mobile#3483]
In the current 2024.2.0 RC, the recording of the child feature of a parent makes the app freeze. This problem is also in production. The app doesn't' freeze when you don't set the name into the district. 

Project:
https://app.merginmaps.com/projects/input-testing/tc05_relations/tree

Scenario:
1) open the project
2) Hit the record button and choose the "district" layer
3) add three points for it and hit "Record". 
4) On the form set the name of the district -> this is needed for the app to freeze. 
5) Hit the + button on the Naturals field
6) record 3 points for Natural and hit "Record" -> Now the app freezes. 

Here is the recording:
https://drive.google.com/file/d/16e6UfrBq8jlYOVIMtbsXJztHy2KFFV0r/view?usp=sharing

**Comment by VitorVieiraZ** [comment]
In any project, if you go to a TextEditor form type, input any text, then switch the focus to another form, e.g., "date," and then try to click on any other button that will move from the current drawer, the app will freeze.

**Comment by jozef-budac** [comment]
Verified on 2024.3.0 RC
