### ISSUE TITLE
While testing a PNG format a warning pops up

### ISSUE THREAD

**Issue by veronikahlinkova** [MerginMaps/mobile#3489]
While testing a PNG format in the 2024.2.0 RC1 a warning pops up.

Test description:
"Check that in all these projects, layers are loaded without any warning, and the map is displayed in input."

Failed project:
https://app.merginmaps.com/projects/input-testing/tc06_png/tree

The warning message:
![IMG_0190](https://github.com/MerginMaps/mobile/assets/171336511/11893e18-021f-4501-9e2f-c326f38ac3fd)
![IMG_0191](https://github.com/MerginMaps/mobile/assets/171336511/ee307f73-6914-416a-90d4-5817337b285d)

**Comment by jozef-budac** [comment]
Good observation. But this is not the problem in this testcase.
