### ISSUE TITLE
Reintroduction of centering to GPS when starting to record new feature

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#3506]
As a follow-up after https://github.com/MerginMaps/mobile/issues/3008 we want  to keep the functionality to center to GPS when going to the recording mode. There should be a new setting in the app to disable this default behavior if one wills.

How it should work:
 - when a user clicks on the "Add" button in the main toolbar, then the map canvas should center to the GPS position (if GPS position is available), unless this behavior is disabled in the app settings

![IMG_6B1CBA11F9A7-1](https://github.com/MerginMaps/mobile/assets/22449698/3da6682a-0358-421e-9c7d-a85d03d3ee26)

 - there should be a new entry in the settings page under the "recording" group with title "Auto-lock position" and description "Each time you start recording, the app centers to GPS". It should be switch component and the value should be true by default. It must be stored in the `AppSettings` too.

---

See how it was implemented previously here ⬇️ https://github.com/MerginMaps/mobile/blob/4b59718bda38cb2215134ca6f713fc944f2367b8/app/qml/map/RecordingTools.qml#L303

**Comment by jozef-budac** [comment]
Verified on 2024.3.0 RC
