### ISSUE TITLE
Editing pipes, the dropdown list has no elements, cannot be clicked

### ISSUE THREAD

**Issue by qianbaidugg** [MerginMaps/mobile#3515]
When editing pipes, the dropdown list has no elements, cannot be clicked, and there is no prompt, which may suspect a phone issue and affect the user experience.
![微信图片_20240621175035](https://github.com/MerginMaps/mobile/assets/71240115/4596d42f-7f55-4221-bdff-eb6866a381b6)

**Comment by tomasMizera** [comment]
Hello @qianbaidugg, sorry, this one slipped through! It seems like your value relation or value map list is empty. Please see https://merginmaps.com/docs/layer/settingup_forms/#select-value-from-a-drop-down-menu
