### ISSUE TITLE
enter aes-256-cbc decryption password，where is password manager?

### ISSUE THREAD

**Issue by jzk-star** [MerginMaps/mobile#3516]
![image](https://github.com/MerginMaps/mobile/assets/83906896/80174e02-bd7e-4d8b-b468-7699c2e5fd80)
![image](https://github.com/MerginMaps/mobile/assets/83906896/535af7b1-9d3e-4141-a7e7-0b64af63555f)
![image](https://github.com/MerginMaps/mobile/assets/83906896/50790926-ca2e-47f7-849b-860fd1169500)

**Comment by tomasMizera** [comment]
Hi @jzk-star, what are you trying to achieve? This is a secret file meant for internal use. You can omit it in your builds by setting `USE_MM_SERVER_API_KEY` cmake variable to `false`. Feel free to reopen the ticket if needed!
