### ISSUE TITLE
Add a new option in the list of industries for students

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#3533]
Add this new option to the list of industries when creating the first workspace.

<img width="222" alt="image" src="https://github.com/user-attachments/assets/8297e141-dcf4-489c-9f30-882da7b5afa7">

Figma: https://www.figma.com/design/d78a4ehBBgK6MyxCTuCAqg/Mobile-App-2.0?node-id=566-14608&t=nQnAOrcWXhgTQQGF-4

`keyword: university`

**Comment by jozef-budac** [comment]
Verified in 2024.3.1 RC
