### ISSUE TITLE
Elide project names from left in the home and explore tabs

### ISSUE THREAD

**Issue by tomasMizera** [MerginMaps/mobile#3536]
In case you have a long workspace name, it is hard to distinguish between projects as most of the row is occupied by the workspace name.

Let's elide (the three dots `...`) from left instead of right so that the workspace name is hidden instead of the project name. This applies to the home and explore tab.

<img src="https://github.com/user-attachments/assets/e7610b61-df3a-48c2-bd9f-a3a835e22043" width=300>

**Comment by jozef-budac** [comment]
Verified in 2024.3.1 RC
