### ISSUE TITLE
Form with Group Box has different text formatting

### ISSUE THREAD

**Issue by geomondego** [MerginMaps/mobile#3565]
On a form with a Group Box container, its title appears with different formatting (bold and size) than other attributes in the table.

Is this normal behavior for this type of container?

![img1](https://github.com/user-attachments/assets/8f465b6b-00c8-48df-9709-6b5e2a764a52)

**Comment by VitorVieiraZ** [comment]
Hello [geomondego](https://github.com/geomondego). Yes, this is the intended behavior for Group Boxes. If you need any further clarification, feel free to reach out.
