### ISSUE TITLE
Multi-tab forms and constraint checks

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#3631]
I have a form with multiple tabs.  if you forget to indicate a unique sample ID (required field), and you scan to a different tab (e.g. to take and upload a photo to a point), when going back to the first tab to make the Station ID a unique field and fill out more information on previous tabs, the tabs are all blank and the point has a red checkmark. This means that we can't save the point with the photo taken and have to re-create the point. This forces users to input info into tab one first and if you forget to make station ID unique the first time you open a new point, you can't save and have to re-enter the point."

**Comment by saberraz** [comment]
To me, it looks like the form validation happens when changing the tab and then it stays in a state of invalid, even after user adds the data and it prevents them to save the form.

**Comment by tomasMizera** [comment]
Hi @saberraz, can you please attach a screencast if you have any?

**Comment by saberraz** [comment]
@tomasMizera let me ask the user

**Comment by tomasMizera** [comment]
Hi @saberraz, we would need a reproducible project or at least definition in not so customer-specific language as this is really hard to understand what is going on. Could we maybe forward this query first to support and ask them to prepare a ticket?

**Comment by saberraz** [comment]
No feedback from reporter. Closed.
