### ISSUE TITLE
Tracking file could not be opened for reading

### ISSUE THREAD

**Issue by Voooo** [MerginMaps/mobile#3641]
Hello,
Tracking worked 2024-10-01 and before on my phone, since 2024-10-02 it doesn't.

When I activate tracking, time starts running but distance remains 0, no yellow line and this shows up. 

"Mergin maps crashes repeatedly" It doesn't close the app, 
![Image](https://github.com/user-attachments/assets/afeb3d56-27c4-4fc9-b856-f801d9a9269c)

I have tried to factory reset my phone, same issue. All my projects works on other devices.
Any Ideas? Thank you.

<img src="https://github.com/user-attachments/assets/4e4f965f-230b-4f9b-a46e-270b1073da19" width=300>
<img src="https://github.com/user-attachments/assets/4d5826a1-ba7c-4886-a025-bcf18a416d8d" width=300>

**Comment by tomasMizera** [comment]
Hello @Voooo, thanks for reporting this! It seems like you are using our beta version `2024.5.0` - can you try removing yourself from the beta testing team? I will also forward your query to our support team for reference.

**Comment by Voooo** [comment]
Hello,
I'll get the same behavior in 2024.4.
There is also some GPS-error

![Image](https://github.com/user-attachments/assets/f978c035-aed2-4f1d-afbf-5165503024d5)

**Comment by raherin** [comment]
@tomasMizera I can confirm that opening any project where a tracking layer is enabled an turning on tracking immediately causes a 'Mergin Maps keeps stopping' message to pop up on my SM-A536B on Mergin Maps 2024.4.0, the same behaviour on my Pixel 6 running MM 2024.5.0

**Comment by raherin** [comment]
To follow up from the previous comment, if I do the same as above on my Pixel 6 but click 'Wait' when the 'Mergin Maps keeps stopping' message appears, the app will continue to work. However, it also added a recording to the layer that was a route not recorded in Mergin Maps. Instead, it was a navigation route I'd followed on Google Maps several weeks before. When I'd followed the route in Google Maps, Mergin Maps had not been running at the time. Furthermore, the recording in Mergin Maps logged the recording as if it had just been done, see the timestamp in the photo below:
![Image](https://github.com/user-attachments/assets/8c8ca0eb-c3cc-4a7c-86b9-d875d1ff1826)

**Comment by tomasMizera** [comment]
Thanks guys for these details, we will have a look at this one with priority!
