### ISSUE TITLE
Keyboard obscures text

### ISSUE THREAD

**Issue by mostlyAtNight** [MerginMaps/mobile#383]
See image below:

![image](https://user-images.githubusercontent.com/884954/61296465-0e83cc00-a7d2-11e9-8084-04119fae7f59.png)

When I added more text to the multi-line edit, it expanded under the keyboard rather than pushing the rest of the form above the keyboard.

**Comment by willrea** [comment]
This is a problem I run into with the current build.

**Comment by jozef-budac** [comment]
This can be simulated in input-testing/forms_widgets project. Steps to reproduce:

1) open input-testing/forms_widgets in INPUT
2) on first "Text" tab go to Multiline field
3) write text with newlines till it reaches the keyboard. All text from now is behind the keyboard or even below it.
