### ISSUE TITLE
Stop/start streaming GPS

### ISSUE THREAD

**Issue by saberraz** [MerginMaps/mobile#516]
It is not very clear to users, that they can use GPS stream to generate lines/polygons. Maybe we should add start/stop stream instead of press and holding GPS sign or a tooltip in the first use.

**Comment by wonder-sk** [comment]
Definitely - the use of GPS button was meant just a quick intermediate fix.

There could be a separate button that appears when line layer is chosen as the survey layer.
We should also think about how to handle it nicely in conjunction with #500
